import { resumeFilename } from './resume-schema.js';
import {$,icon,escapeHTML as e,modal,busy,toast,uid,download,safeURL} from './utils.js';
import {confirmedFacts,transition} from './domain.js';
import {versionAction} from './storage.js';
import {localRequest} from './api.js';
import {resumeHTML} from './resume-builder.js';
export function isDemoDelivery(state,job){return job.source==='demo'||Boolean(state.profile.isSample);}
export function recordDemoDelivery(ctx,job,version){
 const existing=ctx.store.state.applications.find(a=>a.jobId===job.id);
 if(existing&&!existing.isSample)throw new Error('该岗位已有真实投递记录，请选择演示岗位，避免覆盖真实进度');
 const app=recordDelivery(ctx,job,version,{channel:'模拟邮件投递',status:'applied'});
 Object.assign(app,{isSample:true,deliveryState:'simulated',deliveryId:app.deliveryState==='simulated'?app.deliveryId:`DEMO-${uid()}`,notes:app.notes.includes('模拟投递')?app.notes:(app.notes+'\n【模拟投递】仅用于演示，未发送邮件；已关联确认后的简历版本。').trim()});
 ctx.save();return app;
}
function openDemoDelivery(ctx,job,snapshot,version){
 const dialog=modal('投递演示 · 核对这份申请',`<div class="sample-notice">模拟流程 · 不连接邮箱，不向招聘方发送邮件</div><div class="delivery-heading"><h3>${e(job.company)} · ${e(job.title)}</h3><p>01 核对内容 → 02 模拟投递 → 03 手账跟踪</p></div><div class="delivery-preview"><p><b>发件人</b> ${e(snapshot.profile.email||'candidate@example.com')}</p><p><b>收件人</b> careers@example.com（演示邮箱）</p><p><b>标题</b> 应聘 ${e(job.title)} — ${e(snapshot.profile.name)}</p><pre>招聘团队您好：\n我希望应聘贵公司的${e(job.title)}岗位，随附我的简历，期待有机会进一步交流。\n\n${e(snapshot.profile.name)}</pre><p><b>附件</b> ${e(resumeFilename(snapshot.profile,'docx'))} · ${version.facts.length} 项已确认内容</p><button class="button secondary small" id="demo-delivery-word">下载并检查 Word 附件</button></div><details class="delivery-resume"><summary>查看投递简历</summary>${resumeHTML(snapshot.profile,snapshot.resume,{exporting:true})}</details><label class="consent-row"><input type="checkbox" id="confirm-demo-delivery"><span>我已核对简历，开始模拟投递并记录到手账。</span></label><div class="dialog-actions"><button class="button primary" id="send-demo-delivery">确认模拟投递</button></div>`,true);
 $('#demo-delivery-word',dialog).onclick=event=>busy(event.currentTarget,async()=>download(resumeFilename(snapshot.profile,'docx'),await localRequest('/api/resume/docx',snapshot,{blob:true}),'application/vnd.openxmlformats-officedocument.wordprocessingml.document'));
 $('#send-demo-delivery',dialog).onclick=event=>busy(event.currentTarget,async()=>{
  if(!$('#confirm-demo-delivery',dialog).checked)throw new Error('请先勾选核对确认');
  const existing=ctx.store.state.applications.find(a=>a.jobId===job.id);if(existing&&!existing.isSample)throw new Error('该岗位已有真实投递记录，请选择演示岗位');
  await versionAction('put',version);const app=recordDemoDelivery(ctx,job,version);
  dialog.close();const result=modal('模拟投递已完成',`<div class="delivery-heading"><h3>${icon('check',22)} 申请已记入投递手账</h3><p>${e(job.company)} · ${e(job.title)}</p></div><p>已保存投递版简历并关联记录。${app.status==='applied'?'状态已更新为「已投递」。':'该岗位已有后续进展，已保留原状态。'}</p><p class="caption">模拟回执：${e(app.deliveryId)}<br>这是一条本地演示记录，没有发送真实邮件。</p><div class="dialog-actions"><button class="button primary" id="view-demo-application">查看投递记录</button></div>`);
  $('#view-demo-application',result).onclick=()=>{result.close();ctx.router.go('tracker');ctx.openApplication(app.id);};
 },'正在记录模拟投递…');
}
export function recordDelivery(ctx,job,version,{channel,status='saved',receipt=null,to=''}={}){const state=ctx.store.state,now=new Date().toISOString();let app=state.applications.find(a=>a.jobId===job.id);if(!app){app={id:uid(),jobId:job.id,company:job.company,title:job.title,city:job.city,category:job.category,status:'saved',createdAt:now,updatedAt:now,appliedAt:null,history:[{status:'saved',at:now}],notes:'',isSample:job.source==='demo'};state.applications.unshift(app);}Object.assign(app,{resumeVersion:version.id,channel:channel||app.channel||'',applicationUrl:job.url||'',recipient:to||app.recipient||''});if(status==='applied'&&app.status==='saved')Object.assign(app,transition(app,'applied',receipt?.sentAt||now));if(receipt)Object.assign(app,{deliveryId:receipt.messageId,deliveryState:'sent'});ctx.save();return app;}
export async function openDelivery(ctx){try{const state=ctx.store.state,job=ctx.jobById(state.resume.targetJobId);if(!job)throw new Error('先选择具体机会，或导入一个岗位 JD');if(state.resume.facts.some(f=>f.status==='pending'))throw new Error('请确认或移除所有待核实内容后再投递');if(!state.profile.name.trim()||!confirmedFacts(state.resume.facts).length)throw new Error('请填写姓名并核实简历内容');
  const snapshot={profile:structuredClone(state.profile),resume:structuredClone(state.resume)},version={id:uid(),name:`${state.profile.name} · ${job.company} · 投递版`,kind:state.resume.generated?'ai':'manual',savedAt:new Date().toISOString(),profile:snapshot.profile,...snapshot.resume,facts:confirmedFacts(snapshot.resume.facts)};if(isDemoDelivery(state,job)){openDemoDelivery(ctx,job,snapshot,version);return;}await versionAction('put',version);const accounts=(await localRequest('/api/mail/status',{workspaceId:state.agent.workspaceId,applications:state.applications})).accounts;
  const body=`您好：\n我希望应聘贵公司的${job.title}岗位，附件为我的简历。期待进一步沟通，感谢您的时间。\n\n${state.profile.name}`;
  const dialog=modal('为这个机会，递出你的简历',`<div class="delivery-heading"><h3>${e(job.company)} · ${e(job.title)}</h3><p>包含 ${version.facts.length} 条已确认内容，投递版已独立保存。</p></div><section class="delivery-option"><h3>官网投递</h3><p class="caption">打开官网后完成登录和申请表，完成提交后再记录。</p>${safeURL(job.url)?`<a class="button secondary" id="open-application-page" href="${e(safeURL(job.url))}" target="_blank" rel="noopener noreferrer">前往招聘官网 ${icon('external',14)}</a>`:'<p class="caption">该岗位没有原文链接，请补充入口或使用招聘邮箱。</p>'}<button class="button secondary" id="delivery-word">下载投递版 Word</button><button class="text-button" id="confirm-website-application">我已在官网完成提交，记录到手账</button></section><section class="delivery-option"><h3>邮件一键投递</h3><p class="caption">填写招聘方提供的收件地址，预览正文与附件后确认发送。</p>${accounts.length?`<form id="delivery-mail-form"><label class="field">发送邮箱<select name="accountId">${accounts.map(a=>`<option value="${e(a.id)}">${e(a.email)}</option>`).join('')}</select></label><label class="field">招聘收件邮箱<input name="to" type="email" required autocomplete="off"></label><label class="field">邮件标题<input name="subject" maxlength="200" required value="${e(`应聘 ${job.title} — ${state.profile.name}`)}"></label><label class="field">邮件正文<textarea name="text" rows="5" maxlength="10000" required>${e(body)}</textarea></label><button class="button primary">生成投递预览</button></form>`:'<button class="button secondary" id="connect-before-delivery">先连接 QQ / 163 邮箱</button>'}</section>`,true);
  $('#open-application-page',dialog)?.addEventListener('click',()=>{recordDelivery(ctx,job,version,{channel:'招聘官网'});toast('已记录为待投递；官网提交完成后请确认');});
  $('#confirm-website-application',dialog).onclick=()=>{recordDelivery(ctx,job,version,{channel:'招聘官网（用户确认）',status:'applied'});dialog.close();ctx.router.go('tracker');toast('已按你的确认记录为已投递');};
  $('#delivery-word',dialog).onclick=event=>busy(event.currentTarget,async()=>download(resumeFilename(snapshot.profile,'docx'),await localRequest('/api/resume/docx',snapshot,{blob:true}),'application/vnd.openxmlformats-officedocument.wordprocessingml.document'));
  $('#connect-before-delivery',dialog)?.addEventListener('click',()=>{dialog.close();ctx.router.go('settings');});
  const form=$('#delivery-mail-form',dialog);if(form)form.onsubmit=event=>{event.preventDefault();const values=Object.fromEntries(new FormData(form));busy($('button',form),async()=>{const preview=await localRequest('/api/mail/prepare',{workspaceId:state.agent.workspaceId,...values,...snapshot,job});const app=recordDelivery(ctx,job,version,{channel:'邮箱',to:preview.to});previewDelivery(ctx,preview,app);},'正在准备附件…');};
}catch(error){toast(error.message,'error');}}
function previewDelivery(ctx,p,app){const dialog=modal('最后核对一次，再发送',`<div class="delivery-preview"><p><b>发件人</b> ${e(p.from)}</p><p><b>收件人</b> ${e(p.to)}</p><p><b>标题</b> ${e(p.subject)}</p><pre>${e(p.text)}</pre><p><b>附件</b> ${e(p.filename)} · ${Math.ceil(p.attachmentBytes/1024)} KB</p><button class="text-button" id="review-delivery-attachment">下载并检查这份附件</button></div><label class="consent-row"><input type="checkbox" id="confirm-delivery-content"><span>已核对收件邮箱、正文和简历附件，确认发送给该招聘方。</span></label><div class="dialog-actions"><button class="button primary" id="send-delivery">确认发送并记录投递</button></div>`,true);
  $('#review-delivery-attachment',dialog).onclick=event=>busy(event.currentTarget,async()=>download(p.filename,await localRequest('/api/mail/attachment',{workspaceId:ctx.store.state.agent.workspaceId,token:p.token},{blob:true}),'application/vnd.openxmlformats-officedocument.wordprocessingml.document'));
  $('#send-delivery',dialog).onclick=event=>busy(event.currentTarget,async()=>{if(!$('#confirm-delivery-content',dialog).checked)throw new Error('请先核对并勾选发送确认');const state=ctx.store.state;if(!state.agent.pendingSends.some(v=>v.token===p.token))state.agent.pendingSends.push({token:p.token,applicationId:app.id});app.deliveryState='sending';ctx.save();try{const receipt=await localRequest('/api/mail/send',{workspaceId:state.agent.workspaceId,token:p.token,confirmed:true});applyReceipt(ctx,app,receipt);dialog.close();ctx.router.go('tracker');toast('发信服务器已接受邮件，已记录为已投递');}catch(error){app.deliveryState='uncertain';ctx.save();throw error;}},'正在发送，请勿重复点击…');}
function applyReceipt(ctx,app,receipt){if(app.status==='saved')Object.assign(app,transition(app,'applied',receipt.sentAt));Object.assign(app,{deliveryState:'sent',deliveryId:receipt.messageId});ctx.store.state.agent.pendingSends=ctx.store.state.agent.pendingSends.filter(v=>v.token!==receipt.token);ctx.save();}
export async function recoverDeliveries(ctx){for(const pending of ctx.store.state.agent.pendingSends){const app=ctx.store.state.applications.find(a=>a.id===pending.applicationId);if(!app)continue;try{const receipt=await localRequest('/api/mail/receipt',{workspaceId:ctx.store.state.agent.workspaceId,token:pending.token});if(receipt.status==='sent')applyReceipt(ctx,app,receipt);else if(['unknown','uncertain'].includes(receipt.status)){app.deliveryState='uncertain';ctx.save();}}catch{}}}
