import {$,$$,icon,escapeHTML as e,busy,safeURL,toast,dateTime} from './utils.js';
import {localRequest,getLocalService} from './api.js';
// Demo and real workspaces share the same AI-assisted discovery flow. The toggle
// only controls whether we use bundled example jobs or fetch public sources.
export const useWebDiscovery=ctx=>(ctx.store.state.preferences.discoveryMode||(ctx.store.state.profile.isSample?'demo':'web'))==='web';
export function discoveryControls(ctx){const web=useWebDiscovery(ctx);return `<div class="discovery-mode" role="group" aria-label="岗位来源"><button type="button" class="${web?'active':''}" data-discovery-mode="web" aria-pressed="${web}">${icon('search',15)}联网搜索</button><button type="button" class="${!web?'active':''}" data-discovery-mode="demo" aria-pressed="${!web}">示例岗位</button></div><span class="search-mode-note">${web?'AI 搜索真实机会，保留招聘原文':'示例岗位也由 AI 匹配，直接体验求职流程'}</span>`;}
export function sourceSummary(search){if(!search.searchedAt)return `<div class="discovery-welcome">${icon('search',24)}<div><h3>你的下一份机会，从一次搜索开始</h3><p>输入理想职位和城市，找到机会后，就可以为它准备简历。</p></div></div>`;return `<details class="search-report"><summary><span>${icon('check',15)}搜索已完成 · 查看 ${search.sources.length} 个来源与筛选过程</span><time>${dateTime(search.searchedAt)}</time></summary><div class="search-report-body"><div class="search-stages">${search.stages.map(s=>`<span>${e(s.label)} <b>${s.count}</b></span>`).join('<i>→</i>')}</div><p>${e(search.summary)}</p><ul>${search.sources.filter(s=>safeURL(s.url)).map(s=>`<li><a href="${e(safeURL(s.url))}" target="_blank" rel="noopener noreferrer">${e(s.title||new URL(s.url).hostname)} ${icon('external',12)}</a><small>${s.readable?'已读取':'页面受限，可手动查看并导入 JD'}</small></li>`).join('')}</ul></div></details>`;}
let currentSearch=null;
export async function runDiscovery(ctx,button,draw){await busy(button,async()=>{const state=ctx.store.state;if(!state.preferences.query)throw new Error('请填写想找的职位或公司');if(!state.settings.consent)throw new Error('请先在设置中同意发送求职意向至千问');if(state.settings.provider!=='qwen-local')throw new Error('联网搜岗目前使用千问服务，请在设置中选择该服务');currentSearch?.abort();const controller=new AbortController();currentSearch=controller;const progress=$('#discovery-progress');progress.innerHTML=`<div class="agent-running"><span class="loading-dot"></span><div><strong>正在搜索并阅读招聘页面</strong><small>检索来源 → 读取原文 → 筛选岗位；部分官网可能限制访问，约需 1–3 分钟。</small></div><button class="text-button" id="cancel-discovery">取消</button></div>`;$('#cancel-discovery').onclick=()=>controller.abort();
  try{const data=await localRequest('/api/jobs/discover',{preferences:{query:state.preferences.query,skills:state.preferences.skills,city:state.preferences.city,companies:state.preferences.companies,employment:state.preferences.employment},consent:true},{signal:AbortSignal.any([controller.signal,AbortSignal.timeout(getLocalService()?.hosting==='netlify'?1000000:240000)])});if(!Array.isArray(data.jobs))throw new Error('岗位搜索结果不完整，请重试');const jobs=data.jobs.filter(j=>j.source==='web'&&j.id&&safeURL(j.url));for(const job of jobs){const i=state.customJobs.findIndex(j=>j.id===job.id);if(i>=0)state.customJobs[i]=job;else state.customJobs.push(job);}state.agent.search={ids:jobs.map(j=>j.id),summary:data.summary||'',sources:data.sources||[],stages:data.stages||[],searchedAt:data.searchedAt};ctx.save();draw();toast(`搜索完成，找到 ${jobs.length} 个有原文依据的候选岗位`);}catch(error){if(error.name==='AbortError'||error.name==='TimeoutError')throw new Error(controller.signal.aborted?'已取消本次检索':'检索超时，请缩小职位或公司范围后重试');throw error;}finally{if(progress.isConnected)progress.innerHTML='';if(currentSearch===controller)currentSearch=null;}
},'Agent 正在找岗位…');}
