import { $, icon, escapeHTML as e, busy } from './utils.js';
import { funnel, timeline, reminders } from './domain.js';
import { callAI } from './api.js';
import { exportApplications } from './tracker.js';

export function renderInsights(ctx){
  const apps=ctx.store.state.applications,f=funnel(apps),submitted=f[0].count,offers=f.at(-1).count,interviews=f[3].count,pending=reminders(apps).length;
  const interviewRate=submitted?Math.round(interviews/submitted*100):0;
  $('#main-content').innerHTML=`<section class="page-heading"><div><div class="eyebrow">REFLECT & GROW</div><h1>看见进展，<span class="highlight-underline">找到下一步。</span></h1><p>数字不是评价，而是一面镜子。让 AI 结合你的每一条记录，找到更好的方向。</p></div><button class="button secondary" id="insights-export">${icon('download',16)}导出投递数据</button></section><div class="metric-grid">${[{label:'累计投递',value:submitted,note:'包含历史上已进入后续阶段的记录',icon:'briefcase'},{label:'进入面试',value:interviews,note:`面试到达率 ${interviewRate}%`,icon:'people'},{label:'收获 Offer',value:offers,note:`投递到 Offer ${submitted?Math.round(offers/submitted*100):0}%`,icon:'leaf'},{label:'待处理提醒',value:pending,note:'关注回音，也照顾好自己的节奏',icon:'clock'}].map(m=>`<section class="metric-card"><label>${m.label}${icon(m.icon,17)}</label><strong>${String(m.value).padStart(2,'0')}</strong><small>${m.note}</small></section>`).join('')}</div><div class="insights-grid"><section class="panel"><div class="panel-heading"><h2>机会如何一步步靠近</h2><span class="caption">APPLICATION FUNNEL</span></div><p class="caption">按历史到达阶段累计；跳过中间环节时计入已跨过阶段。</p><div class="chart-container"><canvas id="funnel-chart" role="img" aria-label="投递漏斗：${f.map(x=>`${x.label}${x.count}条`).join('，')}"></canvas></div><div class="chart-accessible">${f.map((entry,index)=>`<span>${entry.label} ${entry.count}${index?` · 上一步到达率 ${entry.rate}%`:''}</span>`).join('')}</div></section><section class="panel"><div class="panel-heading"><h2>最近两周的行动足迹</h2><span class="caption">LAST 14 DAYS</span></div><p class="caption">按记录的首次投递日期统计，不含仅收藏的机会。</p><div class="chart-container"><canvas id="timeline-chart" role="img" aria-label="最近14天的每日投递数量"></canvas></div><div class="chart-accessible" id="timeline-text"></div></section><section class="panel"><div class="panel-heading"><h2>写给你的下一步建议</h2><button class="text-button" id="analyze-progress">${icon('sparkle',14)}AI 分析进展</button></div><div id="progress-advice">${adviceHTML(apps,f)}</div></section><section class="panel"><div class="panel-heading"><h2>不同方向的回音</h2><span class="caption">BY ROLE</span></div><p class="caption">按岗位方向比较；样本较少时仅作为记录参考。</p><div class="data-table-wrap"><table class="data-table"><thead><tr><th>方向</th><th>投递</th><th>Offer</th><th>到达率</th></tr></thead><tbody>${groupStats(apps).map(group=>`<tr><td>${e(group.name)}</td><td>${group.applied}</td><td>${group.offers}</td><td>${group.applied?Math.round(group.offers/group.applied*100):0}%</td></tr>`).join('')||'<tr><td colspan="4">记录第一份投递后，就会出现统计。</td></tr>'}</tbody></table></div><p class="caption mt-20">${apps.some(a=>a.isSample)?'当前统计包含示例记录，AI 会一并分析。':'仅统计当前工作区的记录。'}已结束的投递仍保留其历史到达阶段。</p></section></div>`;
  $('#insights-export').onclick=()=>exportApplications(apps);
  $('#analyze-progress').onclick=event=>busy(event.currentTarget,async()=>{
    try{
      const result=await callAI(ctx.store.state.settings,'analysis',{funnel:f,applications:apps.map(a=>({company:a.company,title:a.title,status:a.status,appliedAt:a.appliedAt,history:a.history,isSample:a.isSample}))});
      if(ctx.route!=='insights')return;
      if(!result||typeof result.summary!=='string'||!result.summary.trim())throw new Error('AI 未返回有效的进展分析，请重试');
      $('#progress-advice').innerHTML=`<p class="caption">以下为 AI 建议，请结合实际情况判断。</p><p>${e(result.summary)}</p>${[...(Array.isArray(result.bottlenecks)?result.bottlenecks:[]),...(Array.isArray(result.suggestions)?result.suggestions:[])].slice(0,8).map(s=>`<div class="insight-note">${e(s)}</div>`).join('')}`;
    }catch(error){
      if(ctx.route!=='insights')return;
      $('#progress-advice').innerHTML=`<div class="insight-note" role="alert"><strong>AI 分析未完成</strong><p>${e(error.message||'服务暂时不可用，请稍后重试')}</p><p class="caption">可以再次点击「AI 分析进展」重试。</p></div>`;
      throw error;
    }
  },'分析中…');
  const series=timeline(apps);$('#timeline-text').textContent=series.filter(d=>d.count).map(d=>`${d.date.slice(5)}：${d.count} 次`).join(' · ')||'最近 14 天还没有投递记录。';
  const redraw=()=>{drawFunnel($('#funnel-chart'),f);drawTimeline($('#timeline-chart'),series);};requestAnimationFrame(redraw);
  const observer=new ResizeObserver(()=>{if($('#funnel-chart'))redraw();else observer.disconnect();});observer.observe($('#main-content'));
}
function groupStats(apps){const groups=new Map();for(const app of apps){const name=app.category||'其他';if(!groups.has(name))groups.set(name,[]);groups.get(name).push(app);}return [...groups].map(([name,records])=>{const f=funnel(records);return{name,applied:f[0].count,offers:f.at(-1).count};}).sort((a,b)=>b.applied-a.applied);}
function adviceHTML(apps,f){if(!apps.length)return '<div class="insight-note"><strong>先记下一个感兴趣的机会</strong><p>从发现岗位开始。积累真实记录后，再观察哪些方向更适合自己。</p></div>';const count=f[0].count,rate=count?f[1].count/count:0;const suggestions=[{title:count<10?'还在积累样本，先保持节奏':'让每次投递都有明确方向',text:count<10?`目前累计投递 ${count} 次，样本较少，不适合据此判断长期成功率。`:'对照职位要求优先选择相关经历充分的岗位，记录反馈再逐步调整。'},{title:count&&rate<.4?'把简历与岗位连接得更具体':'把最有说服力的项目讲清楚',text:count&&rate<.4?`当前简历筛选到达率为 ${Math.round(rate*100)}%。可核对关键词、项目相关性与表达清晰度。`:'选择一个真实项目，按背景、行动和可核实结果整理，作为简历和面试的共同素材。'},{title:'给等待中的机会留一个回访时间',text:`当前有 ${reminders(apps).length} 条时间提醒。可以礼貌跟进，同时继续探索其他合适的机会。`}];return '<p class="caption">基于当前记录的本地规则建议，不代表招聘结果预测。</p>'+suggestions.map(s=>`<div class="insight-note"><strong>${s.title}</strong><p>${s.text}</p></div>`).join('');}
function prepare(canvas){if(!canvas)return null;const rect=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1;canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);const c=canvas.getContext('2d');c.scale(dpr,dpr);c.clearRect(0,0,rect.width,rect.height);return{c,w:rect.width,h:rect.height,ink:getComputedStyle(document.documentElement).getPropertyValue('--ink'),muted:getComputedStyle(document.documentElement).getPropertyValue('--muted'),line:getComputedStyle(document.documentElement).getPropertyValue('--line')};}
function drawFunnel(canvas,data){const p=prepare(canvas);if(!p)return;const {c,w,h,ink,muted,line}=p;const left=70,right=36,top=12,barH=22,gap=21,max=Math.max(1,...data.map(x=>x.count)),width=Math.max(50,w-left-right);c.font='12px "Microsoft YaHei", sans-serif';c.fillStyle=muted;c.textAlign='center';for(let t=0;t<=4;t++){const x=left+width*t/4;c.strokeStyle=line;c.beginPath();c.moveTo(x,5);c.lineTo(x,h-27);c.stroke();c.fillText(String(Math.round(max*t/4)),x,h-7);}data.forEach((d,i)=>{const y=top+i*(barH+gap);c.textAlign='right';c.fillStyle=muted;c.fillText(d.label,left-13,y+15);c.fillStyle=['#91a17e','#a9b391','#c0c7a9','#dcc894','#dea851'][i];c.fillRect(left,y,width*d.count/max,barH);c.textAlign='left';c.fillStyle=ink;c.font='12px Consolas, monospace';c.fillText(String(d.count),left+width*d.count/max+7,y+16);c.font='12px "Microsoft YaHei", sans-serif';});}
function drawTimeline(canvas,data){const p=prepare(canvas);if(!p)return;const{c,w,h,muted,line}=p;const left=27,bottom=h-32,top=20,right=w-8,max=Math.max(2,...data.map(x=>x.count)),step=(right-left)/data.length;c.font='11px Consolas, monospace';for(let tick=0;tick<=max;tick++){if(max>6&&tick%Math.ceil(max/5)!==0)continue;const y=bottom-(bottom-top)*tick/max;c.fillStyle=muted;c.textAlign='right';c.fillText(String(tick),left-9,y+3);c.strokeStyle=line;c.beginPath();c.moveTo(left,y);c.lineTo(right,y);c.stroke();}data.forEach((d,i)=>{const x=left+i*step+step*.2,bh=(bottom-top)*d.count/max;c.fillStyle=i===data.length-1?'#dda74d':'#a7b395';c.fillRect(x,bottom-bh,step*.6,bh);c.textAlign='center';if(d.count){c.fillStyle=muted;c.fillText(String(d.count),x+step*.3,bottom-bh-7);}if(i%3===0||i===data.length-1){c.fillStyle=muted;c.fillText(d.date.slice(5).replace('-','/'),x+step*.3,bottom+20);}});}
