import {$,$$,icon,escapeHTML as e,modal,busy,toast,dateTime,toLocalInput} from './utils.js';
import {localRequest,getLocalService} from './api.js';
import {transition,stageLabel} from './domain.js';
const pending=ctx=>ctx.store.state.agent.mailEvents.filter(m=>m.review==='pending');
export const mailPendingCount=ctx=>pending(ctx).length;
const payload=ctx=>({workspaceId:ctx.store.state.agent.workspaceId,applications:ctx.store.state.applications.filter(a=>!a.isSample).map(({id,company,title,status,appliedAt})=>({id,company,title,status,appliedAt}))});
let polling=false;
export function mergeMailbox(ctx,data,{notify=false}={}){ctx.mailAccounts=data.accounts||[];const stored=ctx.store.state.agent.mailEvents,known=new Set(stored.map(m=>m.id)),additions=(data.events||[]).filter(m=>!known.has(m.id));if(additions.length){stored.push(...additions);ctx.store.state.agent.mailEvents=stored.slice(-300);ctx.save();if(notify){toast(`收到 ${additions.length} 条招聘邮件进展，请核对后更新手账`);if(globalThis.Notification?.permission==='granted')new Notification('Jobseeker · 招聘有回音',{body:`有 ${additions.length} 条新进展，打开投递手账查看。`});}}ctx.updateShell();if($('#mail-settings-accounts'))renderAccounts(ctx);if($('#mail-events-count'))$('#mail-events-count').textContent=String(pending(ctx).length);}
export async function refreshMailbox(ctx,{sync=false,notify=true}={}){if(polling)return;polling=true;try{const data=await localRequest(sync?'/api/mail/sync':'/api/mail/status',payload(ctx));mergeMailbox(ctx,data,{notify});return data;}finally{polling=false;}}
export function startMailbox(ctx){if(!getLocalService()?.capabilities?.mail)return;refreshMailbox(ctx,{notify:false}).catch(()=>{});const timer=setInterval(()=>refreshMailbox(ctx).catch(()=>{}),30000);window.addEventListener('pagehide',()=>clearInterval(timer),{once:true});}
export function mailboxSettings(){return `<section class="panel" id="mailbox-panel"><div class="panel-heading"><h2>接住每一份回音</h2>${icon('mail',21)}</div><p class="setting-description">连接 QQ / 163 后，${getLocalService()?.hosting==='netlify'?'云端计划任务约每 2 分钟检查 INBOX（已有任务运行时顺延）':'本机服务每 2 分钟检查 INBOX'}。招聘相关邮件的主题、发件人和正文摘要交给千问识别，进展进入待确认提醒。</p><div id="mail-settings-accounts"></div><form id="connect-mail-form"><div class="form-grid"><label class="field">邮箱服务<select name="provider"><option value="qq">QQ 邮箱 / Foxmail</option><option value="netease">163 邮箱</option></select></label><label class="field">邮箱地址<input name="email" type="email" autocomplete="email" required placeholder="你的邮箱地址"></label></div><label class="field">IMAP/SMTP 授权码<input name="password" type="password" autocomplete="off" required placeholder="开启邮箱服务后生成的授权码"><small>不是登录密码。${getLocalService()?.hosting==='netlify'?'授权码加密保存在云端，断开连接后移除，不进入浏览器备份。':'授权码只留在本机服务内存，重启后需重连，不进入备份。'}</small></label><details class="mail-help"><summary>如何获得授权码？</summary><p>QQ 网页邮箱：设置中查找账户 / POP3、IMAP、SMTP，开启 IMAP/SMTP 并生成授权码。163 网页邮箱：设置中查找 POP3/SMTP/IMAP，开启服务并设置客户端授权码。具体菜单以邮箱页面为准。</p><p>首次检查最近 7 天，每个邮箱每轮最多 ${getLocalService()?.hosting==='netlify'?'8':'50'} 封。不标记已读、不删除邮件；超过 300 KB 的邮件暂不分析。${getLocalService()?.hosting==='netlify'?'云端计划任务在生产发布后运行，关闭页面仍会检查；桌面提醒需要页面打开。':'本机服务关闭后停止检查；桌面提醒还需保持页面打开。'}</p></details><label class="consent-row"><input name="consent" type="checkbox" required><span>允许${getLocalService()?.hosting==='netlify'?'云端服务':'本机'}读取招聘邮件摘要，并发送至已配置的千问识别求职进展。</span></label><button class="button primary">连接邮箱</button></form><div class="button-group mt-20"><button class="button secondary small" id="sync-mail">立即检查邮件</button><button class="text-button" id="enable-mail-notifications">启用桌面提醒</button><button class="text-button" id="settings-mail-events">查看待确认进展</button></div><p class="caption mt-20">邮件发送需在投递预览中由你点击确认。连接邮箱不会发送任何邮件。</p></section>`;}
function renderAccounts(ctx){const node=$('#mail-settings-accounts');if(!node)return;node.innerHTML=(ctx.mailAccounts||[]).map(a=>`<div class="mail-account"><span><strong>${e(a.email)}</strong><small>${a.syncing?'正在检查邮件…':a.lastSync?'上次同步 '+dateTime(a.lastSync):'等待首次同步'}${a.error?' · '+e(a.error):''}</small></span><button class="text-button" data-disconnect-mail="${e(a.id)}">断开连接</button></div>`).join('')||'<p class="caption">尚未连接邮箱；可以同时连接 QQ 和 163。</p>';$$('[data-disconnect-mail]',node).forEach(b=>b.onclick=()=>busy(b,async()=>mergeMailbox(ctx,await localRequest('/api/mail/disconnect',{...payload(ctx),accountId:b.dataset.disconnectMail}))));}
export function bindMailboxSettings(ctx){renderAccounts(ctx);const form=$('#connect-mail-form');form.onsubmit=event=>{event.preventDefault();busy($('button',form),async()=>{const data=Object.fromEntries(new FormData(form));try{mergeMailbox(ctx,await localRequest('/api/mail/connect',{...payload(ctx),...data,consent:data.consent==='on'}));toast('邮箱已连接，后台开始检查招聘邮件');}finally{form.elements.password.value='';}},'正在连接邮箱…');};$('#sync-mail').onclick=event=>busy(event.currentTarget,async()=>{if(!ctx.mailAccounts?.length)throw new Error('请先连接邮箱');await refreshMailbox(ctx,{sync:true});toast('本轮检查结束，请查看账户同步状态和待确认进展');},'正在检查邮件…');$('#settings-mail-events').onclick=()=>showMailEvents(ctx);$('#enable-mail-notifications').onclick=event=>busy(event.currentTarget,async()=>{if(!globalThis.Notification)throw new Error('当前浏览器不支持桌面提醒');const result=await Notification.requestPermission();toast(result==='granted'?'已启用桌面提醒；请保持本页面打开':'未启用桌面提醒，仍可查看页面内提示');});refreshMailbox(ctx,{notify:false}).catch(()=>{});}
export function mailTrackerStrip(ctx){return `<div class="mail-tracker-strip">${icon('mail',19)}<div><strong>招聘邮件进展</strong><span><b id="mail-events-count">${pending(ctx).length}</b> 条待确认 · QQ / 163 邮箱</span></div><button class="button secondary small" id="tracker-mail-events">查看回音</button><button class="text-button" id="tracker-mail-settings">连接邮箱</button></div>`;}
export function bindMailTracker(ctx){$('#tracker-mail-events').onclick=()=>showMailEvents(ctx);$('#tracker-mail-settings').onclick=()=>ctx.router.go('settings');}
export function showMailEvents(ctx){const messages=pending(ctx),apps=ctx.store.state.applications.filter(a=>!a.isSample);const dialog=modal('新的回音，等你核对',`<p class="caption">核对原文证据、对应岗位和时间后再更新手账。</p>${messages.length?messages.map(m=>`<article class="mail-event" data-mail-event="${e(m.id)}"><small>${e(m.from)} · ${dateTime(m.receivedAt)}</small><h3>${e(m.subject)}</h3><p>${e(m.summary)}</p><blockquote>${e(m.evidence)}</blockquote><div class="form-grid"><label class="field">对应投递<select data-mail-app><option value="">请选择公司和岗位</option>${apps.map(a=>`<option value="${e(a.id)}" ${a.id===m.applicationId?'selected':''}>${e(a.company)} · ${e(a.title)}</option>`).join('')}</select></label><label class="field">确认进展<select data-mail-status><option value="unknown">无法确定</option>${['applied','screening','test','interview','offer','rejected'].map(s=>`<option value="${s}" ${m.status===s?'selected':''}>${stageLabel(s)}</option>`).join('')}</select></label></div>${m.eventAt?`<label class="field">邮件提及时间（可编辑，仅面试状态采用）<input type="datetime-local" data-mail-time value="${toLocalInput(m.eventAt)}"></label>`:''}<div class="button-group"><button class="button primary small" data-accept-mail="${e(m.id)}">确认并更新手账</button><button class="text-button" data-dismiss-mail="${e(m.id)}">忽略本条</button></div></article>`).join(''):'<div class="empty-state"><h3>暂时没有新的招聘进展</h3><p>在设置中连接邮箱后，可立即检查。</p></div>'}`,true);
  $$('[data-dismiss-mail]',dialog).forEach(b=>b.onclick=()=>{ctx.store.state.agent.mailEvents.find(m=>m.id===b.dataset.dismissMail).review='dismissed';ctx.save();showMailEvents(ctx);});
  $$('[data-accept-mail]',dialog).forEach(b=>b.onclick=()=>{const m=messages.find(m=>m.id===b.dataset.acceptMail),card=b.closest('[data-mail-event]'),applicationId=$('[data-mail-app]',card).value,status=$('[data-mail-status]',card).value,index=ctx.store.state.applications.findIndex(a=>a.id===applicationId);if(index<0||status==='unknown'){toast('请选择对应投递和确定的进展','error');return;}const app=transition(ctx.store.state.applications[index],status),time=$('[data-mail-time]',card)?.value;if(status==='interview'&&time)app.interviewAt=new Date(time).toISOString();app.notes=(app.notes?app.notes+'\n':'')+`邮件进展（用户确认）：${m.summary}`;ctx.store.state.applications[index]=app;Object.assign(m,{review:'accepted',applicationId,status});ctx.save();showMailEvents(ctx);toast('手账已更新');if(ctx.route==='tracker')ctx.router.refresh();});
}
