import { SECTION_LABELS, PROFILE_LIST_FIELDS, resumeFilename } from './resume-schema.js';
import { $, $$, icon, escapeHTML as e, toast, modal, busy, download, uid, dateTime } from './utils.js';
import { renderResume, resumeHTML, resumeMarkdown } from './resume-builder.js';
import { allVersions, versionAction } from './storage.js';
import { confirmedFacts, profileFacts } from './domain.js';
import { callAI, localRequest } from './api.js';
import { studioViews, studioState, safeProfile, archiveDraft, appendSuggestions, draftFromProfile } from './studio-data.js';

let showTrash=false,libraryQuery='',renderSequence=0;
const labels={original:'导入原件',ai:'AI 定制',manual:'已确认版本',draft:'保留草稿'};
const sectionLabels=SECTION_LABELS;
const strings=value=>Array.isArray(value)?value.filter(v=>typeof v==='string').slice(0,12):[];
const go=(ctx,view)=>{studioState(ctx.store.state).view=view;ctx.save();ctx.router.refresh();};
const nav=view=>`<nav class="studio-tabs" aria-label="简历工作室区域">${studioViews.map(([id,title,glyph])=>`<button data-studio-view="${id}" class="${view===id?'active':''}" ${view===id?'aria-current="page"':''}>${icon(glyph,16)}${title}</button>`).join('')}</nav>`;
function bindNav(ctx){$$('[data-studio-view]').forEach(button=>button.onclick=()=>go(ctx,button.dataset.studioView));}

export function renderStudio(ctx){
  const view=studioState(ctx.store.state).view;renderSequence++;
  if(view==='editor'){renderResume(ctx);$('#main-content').insertAdjacentHTML('afterbegin',nav(view));bindNav(ctx);return;}
  $('#main-content').innerHTML=`${nav(view)}${ctx.store.state.profile.isSample&&ctx.store.state.demoRevision!==2?'<div class="sample-notice">新版演示已加入口语素材、专业改写和完整投递流程。<a class="text-button" href="#/settings">前往设置 → 重置演示数据</a></div>':''}<section class="page-heading studio-heading"><div><div class="eyebrow">YOUR STORY, TAKING SHAPE</div><h1>把每一段经历，<span class="highlight-underline">写成下一种可能。</span></h1><p>积累素材，打磨表达，为不同的机会准备不同版本。</p></div><span class="studio-stamp">${icon('leaf',26)}<span>真实的你<br>值得被看见</span></span></section><div id="studio-content"></div>`;
  bindNav(ctx);
  if(view==='library')renderLibrary(ctx,renderSequence).catch(error=>toast(error.message,'error'));
  else if(view==='materials')renderMaterials(ctx);
  else renderCoach(ctx);
}
async function renderLibrary(ctx,sequence){
  const all=await allVersions({includeTrash:true});if(sequence!==renderSequence||ctx.route!=='resume')return;
  const active=all.filter(v=>!v.deletedAt),trash=all.filter(v=>v.deletedAt);
  $('#studio-content').innerHTML=`<div class="studio-workflow"><button data-go="materials"><span>01</span><strong>整理个人素材</strong><small>记录经历与真实成果</small>${icon('arrow',16)}</button><button data-go="editor"><span>02</span><strong>生成专属简历</strong><small>选定岗位 · 核实内容</small>${icon('arrow',16)}</button><button data-go="coach"><span>03</span><strong>诊断与优化</strong><small>让每一版更有针对性</small>${icon('sparkle',17)}</button></div><section class="library-panel"><div class="library-toolbar"><div><h2>${showTrash?'回收站':'我的简历库'} <span class="caption">${showTrash?trash.length:active.length} 个版本</span></h2><p class="caption">原始资料与定制版本独立保存，拖动卡片可调整顺序。</p></div><div class="button-group"><button class="text-button" id="library-help" aria-label="简历库使用说明">使用说明</button><button class="button secondary small" id="toggle-trash">${showTrash?'返回简历库':`回收站 (${trash.length})`}</button><button class="button secondary small" id="import-resume">${icon('upload',14)}导入简历</button><button class="button primary small" id="continue-draft">${icon('plus',14)}继续编辑草稿</button></div></div><label class="library-search">${icon('search',16)}<input id="library-search" aria-label="搜索简历版本" placeholder="按名称或目标公司查找版本" value="${e(libraryQuery)}"></label><div class="resume-wall" id="resume-wall"></div><input type="file" id="resume-upload" accept=".pdf,.docx,.txt,.md" hidden><div class="wall-legend"><span><i></i>导入原件</span><span><i class="ai"></i>AI 定制</span><span>保存在当前浏览器 · 可在设置中完整备份</span></div></section>`;
  $$('[data-go]').forEach(b=>b.onclick=()=>go(ctx,b.dataset.go));
  $('#continue-draft').onclick=()=>go(ctx,'editor');
  $('#toggle-trash').onclick=()=>{showTrash=!showTrash;renderStudio(ctx);};
  $('#library-help').onclick=()=>modal('让每个机会，都有合适的一版',`<div class="pre-wrap">导入原件：保留 PDF、Word 或文本文件中提取的原文，原文件不上传云端。\nAI 定制：在编辑器中核实内容后保存，独立于原始资料。\n保留草稿：切换版本前自动保存，未确认内容仍需核实。\n拖动卡片调整排列，也可使用卡片上的「前移」按钮。\n移入回收站后可以恢复，投递记录已有的关联 ID 不会改变。</div>`);
  $('#import-resume').onclick=()=>$('#resume-upload').click();
  $('#resume-upload').onchange=event=>{const file=event.target.files[0];event.target.value='';if(file)busy($('#import-resume'),()=>importFile(ctx,file),'读取中…');};
  const draw=()=>{
    const items=(showTrash?trash:active).filter(v=>v.name.toLowerCase().includes(libraryQuery.toLowerCase())).sort((a,b)=>(a.order||0)-(b.order||0));
    $('#resume-wall').innerHTML=(!showTrash&&!libraryQuery?`<button class="draft-card" id="draft-card"><span class="draft-badge">正在编辑</span>${icon('edit',32)}<h3>${e(ctx.store.state.profile.name||'我的')}的下一版简历</h3><p>从已有档案继续，<br>把经历整理成清晰的表达。</p><span class="text-button">打开编辑器 ${icon('arrow',15)}</span></button>`:'')+items.map(v=>`<article class="library-card kind-${e(v.kind||'manual')}" draggable="${!showTrash}" data-version="${e(v.id)}"><div class="library-card-top"><span>${labels[v.kind]||labels.manual}</span><span>${dateTime(v.savedAt)}</span></div><button class="paper-thumbnail" data-preview="${e(v.id)}" aria-label="预览 ${e(v.name)}"><strong>${e(v.profile?.name||v.sourceFilename||'我的简历')}</strong><small>${e(v.profile?.role||'原始资料')}</small><div class="mini-rule"></div>${v.sourceText?`<p>${e(v.sourceText.slice(0,350))}</p>`:v.facts.slice(0,4).map(f=>`<h4>${sectionLabels[f.section]||''}</h4><p>${e(f.text.slice(0,150))}</p>`).join('')}</button><h3 title="${e(v.name)}">${e(v.name)}</h3><p class="caption">${v.sourceText?'保留提取原文':`${confirmedFacts(v.facts).length} 项已确认内容`}</p><div class="card-actions">${showTrash?`<button data-restore-trash="${e(v.id)}">恢复版本</button>`:`<button data-preview="${e(v.id)}">打开</button><button data-review="${e(v.id)}">AI 诊断</button><button data-move="${e(v.id)}" aria-label="前移 ${e(v.name)}">前移</button><button data-trash="${e(v.id)}" aria-label="移入回收站 ${e(v.name)}">移除</button>`}</div></article>`).join('')+(!items.length&&(showTrash||libraryQuery)?'<div class="wall-empty">这里暂时没有简历版本。</div>':'');
    $('#draft-card')?.addEventListener('click',()=>go(ctx,'editor'));
    $$('[data-preview]').forEach(b=>b.onclick=()=>openVersion(ctx,all.find(v=>v.id===b.dataset.preview)));
    $$('[data-review]').forEach(b=>b.onclick=()=>reviewDialog(ctx,all.find(v=>v.id===b.dataset.review)));
    for(const [attr,deleted] of [['trash',true],['restore-trash',false]])$$(`[data-${attr}]`).forEach(b=>b.onclick=()=>busy(b,async()=>{const v=all.find(v=>v.id===b.getAttribute(`data-${attr}`));await versionAction('put',{...v,deletedAt:deleted?new Date().toISOString():null});renderStudio(ctx);toast(deleted?'已移入回收站，可随时恢复':'版本已恢复');}));
    const reorder=async(from,to)=>{const arranged=[...active].sort((a,b)=>(a.order||0)-(b.order||0));const index=arranged.findIndex(v=>v.id===from),target=arranged.findIndex(v=>v.id===to);if(index<0||target<0||index===target)return;arranged.splice(target,0,arranged.splice(index,1)[0]);for(let i=0;i<arranged.length;i++){arranged[i].order=i;await versionAction('put',arranged[i]);}draw();};
    $$('[data-move]').forEach(b=>b.onclick=()=>busy(b,()=>reorder(b.dataset.move,items[0].id)));
    $$('.library-card').forEach(card=>{card.ondragstart=event=>{event.dataTransfer.setData('text/plain',card.dataset.version);event.dataTransfer.effectAllowed='move';};card.ondragover=event=>event.preventDefault();card.ondrop=event=>{event.preventDefault();reorder(event.dataTransfer.getData('text/plain'),card.dataset.version).catch(error=>toast(error.message,'error'));};});
  };
  $('#library-search').oninput=event=>{libraryQuery=event.target.value;draw();};draw();
}
function openVersion(ctx,v){
  const dialog=modal(v.name,`<p class="caption">${labels[v.kind]||labels.manual} · ${dateTime(v.savedAt)}</p><div class="button-group version-tools">${v.sourceText?'<button class="button primary small" id="parse-original">AI 提取为个人档案</button>':'<button class="button primary small" id="edit-version">编辑此版本</button><button class="button secondary small" id="version-md">Markdown</button><button class="button secondary small" id="version-docx">Word</button>'}<button class="button secondary small" id="version-review">AI 诊断 / 岗位匹配</button><button class="text-button" id="rename-version">重命名</button></div>${v.sourceText?`<pre class="original-text">${e(v.sourceText)}</pre>`:resumeHTML(v.profile,v,{exporting:true})}`,true);
  $('#version-review',dialog).onclick=()=>reviewDialog(ctx,v);
  $('#rename-version',dialog).onclick=()=>{const d=modal('重命名版本',`<form id="rename-form"><label class="field">版本名称<input name="name" maxlength="200" required value="${e(v.name)}"></label><button class="button primary">保存名称</button></form>`);$('#rename-form',d).onsubmit=event=>{event.preventDefault();busy($('button[type=submit]',d)||$('#rename-form button',d),async()=>{const name=event.currentTarget.elements.name.value.trim();if(!name)throw new Error('请填写名称');await versionAction('put',{...v,name});d.close();renderStudio(ctx);});};};
  $('#parse-original',dialog)?.addEventListener('click',event=>busy(event.currentTarget,()=>parseOriginal(ctx,v),'AI 提取中…'));
  $('#edit-version',dialog)?.addEventListener('click',event=>busy(event.currentTarget,async()=>{await archiveDraft(ctx);ctx.store.state.profile=structuredClone(v.profile);ctx.store.state.resume={...ctx.store.state.resume,facts:structuredClone(v.facts),template:v.template,targetJobId:v.targetJobId||'',customJD:v.customJD||'',instruction:v.instruction||'',generated:true};dialog.close();go(ctx,'editor');toast('已打开此版本，之前的草稿已保留到简历库');}));
  $('#version-md',dialog)?.addEventListener('click',()=>download(resumeFilename(v.profile,'md'),resumeMarkdown(v.profile,v),'text/markdown;charset=utf-8'));
  $('#version-docx',dialog)?.addEventListener('click',event=>busy(event.currentTarget,async()=>download(resumeFilename(v.profile,'docx'),await localRequest('/api/resume/docx',{profile:v.profile,resume:v},{blob:true}),'application/vnd.openxmlformats-officedocument.wordprocessingml.document'),'导出中…'));
}
async function importFile(ctx,file){
  if(file.size>8*1024*1024)throw new Error('单个文件最大 8 MB');
  const content=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('无法读取文件'));reader.readAsDataURL(file);});
  const data=await localRequest('/api/resume/extract',{filename:file.name,content});
  const dialog=modal('核对导入的简历原文',`<p class="caption">${e(data.filename)} · ${data.characters} 字符。文字由文档服务提取，尚未发送给 AI。</p><label class="field">提取内容<textarea id="import-text" rows="14" maxlength="100000">${e(data.text)}</textarea></label><div class="dialog-actions"><button class="button primary" id="save-original">保存到简历库</button></div>`,true);
  $('#save-original',dialog).onclick=event=>busy(event.currentTarget,async()=>{const sourceText=$('#import-text',dialog).value.trim();if(!sourceText)throw new Error('简历原文不能为空');const version={id:uid(),name:file.name.replace(/\.[^.]+$/,''),kind:'original',savedAt:new Date().toISOString(),profile:safeProfile({}),facts:[],template:'general',targetJobId:'',sourceText,sourceFilename:file.name};await versionAction('put',version);dialog.close();showTrash=false;libraryQuery='';go(ctx,'library');toast('原始简历已保存，可打开后选择 AI 提取或诊断');});
}
async function parseOriginal(ctx,v){
  const result=await callAI(ctx.store.state.settings,'resumeParse',{text:v.sourceText});if(!result?.profile||typeof result.profile!=='object')throw new Error('AI 未返回有效档案，请重试');
  const profile=safeProfile(result.profile);profile.isSample=false;
  const dialog=modal('核对 AI 提取结果',`<p class="caption">对照原文核实后再使用。现有档案与草稿会自动保留为独立版本。</p><div class="parse-fields">${Object.entries({name:'姓名',role:'职业方向',email:'邮箱',phone:'电话',city:'城市',website:'作品集',github:'GitHub',blog:'技术博客',skills:'技能',summary:'简介'}).map(([key,label])=>`<p><strong>${label}</strong><span>${e(profile[key]||'未识别')}</span></p>`).join('')}</div>${Object.keys(PROFILE_LIST_FIELDS).map(section=>`<h3>${sectionLabels[section]||'技能分类'}</h3>${profile[section].map(item=>`<p class="pre-wrap">${e(Object.values(item).filter(Boolean).join(' · '))}</p>`).join('')||'<p class="caption">未识别</p>'}`).join('')}<p class="pre-wrap caption">${e(strings(result.warnings).join('\n'))}</p><div class="dialog-actions"><button class="button primary" id="apply-import">已核对，导入编辑器</button></div>`,true);
  $('#apply-import',dialog).onclick=event=>busy(event.currentTarget,async()=>{await archiveDraft(ctx);ctx.store.state.profile=profile;ctx.store.state.resume=draftFromProfile(profile,ctx.store.state.resume);dialog.close();go(ctx,'editor');toast('已采用你核对后的导入档案，可继续编辑和定制');});
}
function reviewDialog(ctx,v){
  const dialog=modal('简历诊断 · 找到下一步',`<p class="caption">${e(v.name)}。点击后会把简历内容和目标 JD 交给 AI，结果请结合实际情况核对。</p><label class="field">目标岗位 JD（可选）<textarea id="review-jd" rows="4" maxlength="15000" placeholder="粘贴岗位职责与要求，获得更具体的匹配建议"></textarea></label><button class="button primary" id="run-review">${icon('sparkle',16)}开始诊断</button><div id="review-result" aria-live="polite"></div>`,true);
  $('#run-review',dialog).onclick=event=>busy(event.currentTarget,async()=>{
    const resultNode=$('#review-result',dialog),jd=$('#review-jd',dialog).value.trim();const r=await callAI(ctx.store.state.settings,'resumeReview',{profile:v.profile,facts:v.facts,text:v.sourceText||'',job:jd});
    if(!r||typeof r.summary!=='string')throw new Error('AI 未返回有效诊断，请重试');if(!dialog.open||!resultNode.isConnected)return;
    resultNode.innerHTML=`<div class="review-overview">${Number.isFinite(r.score)?`<strong>${Math.round(Math.max(0,Math.min(100,r.score)))}<small>/100</small></strong>`:icon('shield',28)}<div><h3>AI 内容诊断</h3><p>${e(r.summary)}</p><small>仅供内容优化参考，不是录用概率或官方 ATS 分数。</small></div></div>${strings(r.strengths).length?`<h3>已经做得不错</h3><ul>${strings(r.strengths).map(t=>`<li>${e(t)}</li>`).join('')}</ul>`:''}${(Array.isArray(r.issues)?r.issues:[]).slice(0,6).map(i=>`<section class="review-issue"><h3>${e(i.title)}</h3><p class="caption">依据：${e(i.evidence)}</p><p>${e(i.suggestion)}</p></section>`).join('')}<div class="keyword-columns"><div><h3>已体现关键词</h3>${strings(r.keywords?.matched).map(t=>`<span class="skill-tag">${e(t)}</span>`).join('')||'<p class="caption">暂无</p>'}</div><div><h3>仍需证据支撑</h3>${strings(r.keywords?.missing).map(t=>`<span class="skill-tag">${e(t)}</span>`).join('')||'<p class="caption">暂无</p>'}</div></div><h3>接下来可以做</h3><ol>${strings(r.nextSteps).map(t=>`<li>${e(t)}</li>`).join('')}</ol>`;
  },'正在阅读简历…');
}
function renderMaterials(ctx){
  const studio=studioState(ctx.store.state);
  $('#studio-content').innerHTML=`<div class="materials-layout"><section class="panel"><div class="panel-heading"><h2>值得写下的经历</h2>${icon('list',23)}</div><p class="setting-description">一个解决过的问题，一次团队协作，一项真实成果。先记录，再整理。</p><form id="material-form"><label class="field">素材标题<input name="title" required maxlength="200" placeholder="例如：为课程项目做了一次性能优化"></label><label class="field">归入简历栏目<select name="section">${Object.entries(sectionLabels).map(([id,label])=>`<option value="${id}" ${id==='projects'?'selected':''}>${label}</option>`).join('')}</select></label><label class="field">原始经历<textarea name="text" required rows="9" maxlength="8000" placeholder="当时遇到什么问题？你负责什么？采取了哪些行动？最后有什么可以验证的结果？"></textarea></label><div class="button-group"><button class="button primary">保存素材</button><button type="button" class="button secondary" id="structure-star">${icon('sparkle',15)}STAR 整理</button></div><div id="star-result" aria-live="polite"></div></form></section><section><div class="materials-header"><h2>我的素材夹 <span class="caption">${studio.materials.length} 条</span></h2><p class="caption">定制简历时会结合这里的素材，AI 表达仍需核实。</p></div><div class="material-list">${studio.materials.length?studio.materials.map(m=>`<article class="material-note"><div class="caption">${sectionLabels[m.section]} · ${dateTime(m.savedAt)}</div><h3>${e(m.title)}</h3><p class="pre-wrap">${e(m.text)}</p><div class="button-group"><button class="text-button" data-edit-material="${e(m.id)}">编辑素材</button><button class="text-button" data-use-material="${e(m.id)}">加入待核实简历</button></div></article>`).join(''):'<div class="material-note empty-state">'+icon('leaf',30)+'<h3>好的表达，来自真实细节</h3><p>从一段最熟悉的经历开始。</p></div>'}</div></section></div>`;
  const form=$('#material-form');let editingId='';
  form.onsubmit=event=>{event.preventDefault();const data=new FormData(form),entry={id:editingId||uid(),title:data.get('title').trim(),text:data.get('text').trim(),section:data.get('section'),savedAt:new Date().toISOString()};if(!entry.text||!entry.title)return;if(!editingId&&studio.materials.length>=50){toast('素材夹最多保存 50 条，请先编辑已有素材','error');return;}const index=studio.materials.findIndex(m=>m.id===editingId);if(index>=0)studio.materials[index]=entry;else studio.materials.unshift(entry);ctx.save();renderMaterials(ctx);toast('素材已保存');};
  $$('[data-edit-material]').forEach(b=>b.onclick=()=>{const m=studio.materials.find(m=>m.id===b.dataset.editMaterial);editingId=m.id;for(const key of ['title','text','section'])form.elements[key].value=m[key];form.elements.title.focus();});
  $$('[data-use-material]').forEach(b=>b.onclick=()=>{const m=studio.materials.find(m=>m.id===b.dataset.useMaterial);if(ctx.store.state.resume.facts.some(f=>f.text===m.text)){toast('这条素材已在简历中');return;}ctx.store.state.resume.facts.push({id:uid(),section:m.section,text:m.text,source:'USER',sourceRef:`素材夹 · ${m.title}`,status:'pending'});ctx.store.state.resume.generated=true;ctx.save();toast('已加入编辑器，核实并确认后可导出');});
  $('#structure-star').onclick=event=>busy(event.currentTarget,async()=>{const text=form.elements.text.value.trim();if(!text)throw new Error('先写下一段真实经历');const r=await callAI(ctx.store.state.settings,'star',{text,section:form.elements.section.value});if(!r||typeof r.action!=='string')throw new Error('AI 未返回有效 STAR 内容');if(!$('#star-result'))return;$('#star-result').innerHTML=`<div class="star-result">${[['S','背景',r.situation],['T','任务',r.task],['A','行动',r.action],['R','结果',r.result]].map(([letter,title,value])=>`<div><b>${letter}</b><p><strong>${title}</strong><span>${e(value||'原文尚未提供')}</span></p></div>`).join('')}<p class="caption">待补充：${e(strings(r.missing).join('；')||'请核对以上表述')}</p><button class="button secondary small" type="button" id="apply-star">加入简历待核实区</button></div>`;$('#apply-star').onclick=()=>{try{const facts=(Array.isArray(r.facts)?r.facts:[]).map(f=>({...f,section:form.elements.section.value}));const n=appendSuggestions(ctx,facts);toast(`已加入 ${n} 条待核实内容`);}catch(error){toast(error.message,'error');}};},'正在整理 STAR…');
}
function renderCoach(ctx){
  const studio=studioState(ctx.store.state),state=ctx.store.state;
  $('#studio-content').innerHTML=`<div class="coach-layout"><aside class="panel coach-context"><span class="coach-avatar">${icon('sparkle',28)}</span><h2>一起把经历讲清楚。</h2><p class="setting-description">与 AI 对话，围绕你的档案和素材逐步打磨。</p><div class="coach-context-row"><small>当前档案</small><strong>${e(state.profile.name||'尚未填写姓名')}</strong><span>${e(state.profile.role||'尚未选择方向')}</span></div><div class="coach-context-row"><small>可用素材</small><span>${studio.materials.length} 条个人素材 · ${state.resume.facts.length} 条简历内容</span></div><button class="button secondary" id="diagnose-current">诊断当前简历</button><p class="caption mt-20">提问时会发送当前档案、简历、素材和最近对话。AI 改写可加入待核实区，确认后再导出。</p></aside><section class="coach-panel"><div class="coach-topline"><strong>简历顾问</strong><span>AI · ${e(state.settings.model||'云端服务')}</span></div><div class="coach-messages" id="coach-messages">${studio.messages.length?studio.messages.map((m,i)=>`<article class="coach-message ${m.role}"><small>${m.role==='user'?'你':'简历顾问'}</small><div class="pre-wrap">${e(m.text)}</div>${m.suggestedFacts?.length?`<div class="coach-suggestions">${m.suggestedFacts.map(f=>`<p>${e(f.text)}</p>`).join('')}<button class="text-button" data-apply-coach="${i}">加入简历待核实区</button></div>`:''}</article>`).join(''):`<div class="coach-welcome">${icon('sparkle',35)}<h3>从一个具体问题开始</h3><p>你可以问我怎样突出项目贡献、整理实习经历，<br>或根据目标岗位调整简历重点。</p></div>`}</div><div class="coach-prompts">${['帮我找出当前简历最需要改善的三处','如何把项目经历写得更具体？','请润色我的个人简介，不增加事实'].map(t=>`<button data-prompt="${e(t)}">${e(t)}</button>`).join('')}</div><form id="coach-form"><label class="field"><span class="sr-only">向简历顾问提问</span><textarea name="question" rows="3" required maxlength="3000" placeholder="说说你想改进哪段经历…"></textarea></label><button class="button primary" type="submit">发送 ${icon('arrow',16)}</button></form></section></div>`;
  $('#diagnose-current').onclick=()=>reviewDialog(ctx,{name:'当前编辑草稿',profile:state.profile,...state.resume});
  const form=$('#coach-form');$$('[data-prompt]').forEach(b=>b.onclick=()=>{form.elements.question.value=b.dataset.prompt;form.elements.question.focus();});
  $$('[data-apply-coach]').forEach(b=>b.onclick=()=>{try{toast(`已加入 ${appendSuggestions(ctx,studio.messages[Number(b.dataset.applyCoach)].suggestedFacts)} 条待核实内容`);}catch(error){toast(error.message,'error');}});
  form.onsubmit=event=>{event.preventDefault();const question=form.elements.question.value.trim();if(!question)return;busy($('button[type=submit]',form),async()=>{const answer=await callAI(state.settings,'resumeCoach',{question,profile:state.profile,facts:state.resume.facts,materials:studio.materials,job:state.resume.targetJobId==='custom'?state.resume.customJD:ctx.jobById(state.resume.targetJobId),messages:studio.messages.slice(-10).map(({role,text})=>({role,text}))});if(!answer||typeof answer.answer!=='string')throw new Error('AI 未返回有效回答，请重试');studio.messages.push({role:'user',text:question},{role:'assistant',text:answer.answer+(strings(answer.followUps).length?'\n\n可以继续想一想：\n'+strings(answer.followUps).join('\n'):''),suggestedFacts:Array.isArray(answer.suggestedFacts)?answer.suggestedFacts.slice(0,3):[]});studio.messages=studio.messages.slice(-30);ctx.save();if(ctx.route==='resume'&&studio.view==='coach'){renderCoach(ctx);$('#coach-messages').scrollTop=$('#coach-messages').scrollHeight;}},'正在思考…');};
}
