import { $, $$, icon, escapeHTML as e, toast, modal, uid, displayDate, dateTime, localDate, toLocalInput, download, csv, emptyState, busy } from './utils.js';
import { STAGES, stageLabel, transition, reminders, guessEmailStatus } from './domain.js';
import { allVersions } from './storage.js';
import { companyMark } from './job-search.js';
import { mailTrackerStrip,bindMailTracker } from './mail-ui.js';

let currentView='board',filter='',hideEmpty=false,hideEnded=false;
export function renderTracker(ctx){
  const state=ctx.store.state;const notices=reminders(state.applications);
  $('#main-content').innerHTML=`<div class="tracker-page">
    <section class="page-heading tracker-heading"><div><div class="eyebrow">ONE STEP CLOSER</div><h1>每一步进展，<span class="highlight-underline">都值得记下。</span></h1><p>把机会排好，把下一步看清。</p></div><div class="button-group"><button class="button secondary" id="export-tracker">${icon('download',16)}导出 CSV</button><button class="button primary" id="new-application">${icon('plus',16)}记录新机会</button></div></section>
    <nav id="tracker-stage-overview" class="tracker-stage-overview" aria-label="投递阶段概览"></nav>
    <div class="tracker-utilities ${notices.length?'has-reminders':''}">${notices.length?`<div class="reminder-strip">${icon('clock',17)}<div><strong>${notices.length} 条待办提醒</strong><span title="${e(notices[0].title)}">${e(notices[0].title)}${notices.length>1?'等':''}</span></div><button class="text-button" id="tracker-reminders">查看提醒 ${icon('arrow',14)}</button></div>`:''}${mailTrackerStrip(ctx)}</div>
    <div class="tracker-toolbar"><div class="view-switch" aria-label="投递视图"><button data-view="board" class="${currentView==='board'?'active':''}" aria-pressed="${currentView==='board'}">${icon('board',15)}看板</button><button data-view="list" class="${currentView==='list'?'active':''}" aria-pressed="${currentView==='list'}">${icon('list',15)}列表</button><button id="tracker-insights">${icon('chart',15)}数据洞察</button></div><label class="tracker-search-field">${icon('search',17)}<input id="tracker-search" aria-label="搜索投递记录" placeholder="搜索公司或职位…" value="${e(filter)}"></label></div>
    <div class="tracker-board-options" ${currentView==='board'?'':'hidden'}><div><label><input id="tracker-hide-empty" type="checkbox" ${hideEmpty?'checked':''}>隐藏空列</label><label><input id="tracker-hide-ended" type="checkbox" ${hideEnded?'checked':''}>收起已结束</label></div><span id="tracker-board-summary" aria-live="polite"></span></div>
    <div id="tracker-content"></div><p class="caption tracker-footnote">${icon('shield',13)}${currentView==='board'?'拖拽卡片或选择状态更新进度，点击上方阶段可快速定位。':'点击记录查看详情与状态时间线。'}含「演示」标记的记录仅供体验。</p>
  </div>`;
  bindMailTracker(ctx);
  $('#new-application').onclick=()=>openApplication(ctx);
  $('#export-tracker').onclick=()=>exportApplications(state.applications);
  $('#tracker-reminders')?.addEventListener('click',()=>$('#notifications-button').click());
  $('#tracker-insights').onclick=()=>ctx.router.go('insights');
  $$('[data-view]').forEach(el=>el.onclick=()=>{currentView=el.dataset.view;renderTracker(ctx);});
  $('#tracker-search').oninput=event=>{filter=event.target.value;drawTracker(ctx);};
  $('#tracker-hide-empty').onchange=event=>{hideEmpty=event.target.checked;drawTracker(ctx);};
  $('#tracker-hide-ended').onchange=event=>{hideEnded=event.target.checked;drawTracker(ctx);};
  drawTracker(ctx);
}
function drawTracker(ctx){
  const apps=ctx.store.state.applications.filter(a=>`${a.company} ${a.title}`.toLowerCase().includes(filter.trim().toLowerCase()));
  const content=$('#tracker-content');
  const priorScroll=$('.board-scroll',content)?.scrollLeft||0;
  const visibleStages=STAGES.filter(stage=>(!hideEmpty||apps.some(a=>a.status===stage.id))&&(!hideEnded||stage.id!=='rejected'));
  $('#tracker-stage-overview').innerHTML=STAGES.map(stage=>{const count=apps.filter(a=>a.status===stage.id).length;return `<button class="tracker-stage ${['interview','offer'].includes(stage.id)?'priority-stage':''}" data-jump-stage="${stage.id}" style="--stage-color:${stage.color}" aria-label="查看${stage.label}，${count} 条记录"><span><i></i>${stage.label}</span><strong>${count}<small>份</small></strong></button>`;}).join('');
  $('#tracker-board-summary').textContent=`${filter.trim()?'找到':'共'} ${apps.length} 份机会 · ${visibleStages.length} 个阶段展开`;
  $$('[data-jump-stage]').forEach(button=>button.onclick=()=>{
    const stage=button.dataset.jumpStage;
    if(hideEmpty&&!apps.some(a=>a.status===stage))hideEmpty=false;
    if(stage==='rejected')hideEnded=false;
    if(currentView!=='board'){currentView='board';renderTracker(ctx);}else{
      $('#tracker-hide-empty').checked=hideEmpty;
      $('#tracker-hide-ended').checked=hideEnded;
      drawTracker(ctx);
    }
    const column=$(`[data-stage="${stage}"]`,content.isConnected?content:$('#tracker-content'));
    const scroll=$('.board-scroll');
    if(column&&scroll){
      const left=scroll.scrollLeft+column.getBoundingClientRect().left-scroll.getBoundingClientRect().left;
      scroll.scrollTo({left,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
      column.focus({preventScroll:true});
    }
  });
  const options=app=>STAGES.map(s=>`<option value="${s.id}" ${app.status===s.id?'selected':''}>${s.label}</option>`).join('');
  if(currentView==='board')content.innerHTML=visibleStages.length?`<div class="board-scroll" role="region" aria-label="投递看板，可横向滚动" tabindex="0"><div class="kanban-board" style="--visible-stage-count:${visibleStages.length}">${visibleStages.map(stage=>{const list=apps.filter(a=>a.status===stage.id).sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt));return `<section class="board-column" data-stage="${stage.id}" aria-label="${stage.label}列" tabindex="-1"><header class="column-heading"><span class="column-dot" style="--stage-color:${stage.color}"></span><strong>${stage.label}</strong><small>${list.length}</small><button data-new-stage="${stage.id}" aria-label="新增${stage.label}记录">${icon('plus',15)}</button></header>${list.map(app=>`<article class="application-card" draggable="true" data-drag="${e(app.id)}"><button data-open-application="${e(app.id)}"><span class="application-company">${companyMark(ctx.jobById(app.jobId)||{company:app.company,tone:'sage'})}<span>${e(app.company)}</span></span><h3>${e(app.title)}</h3><p>${e(app.city||'地点未填写')}${app.isSample?' · 演示':''}${app.resumeVersion?' · 已关联简历':''}${app.deliveryState==='simulated'?' · 模拟投递':app.deliveryState==='uncertain'?' · 发送结果待核实':app.deliveryState==='sending'?' · 正在发送':''}</p>${app.status==='interview'&&app.interviewAt?`<p class="application-deadline">${icon('clock',13)} ${dateTime(app.interviewAt)}</p>`:''}${app.status==='offer'&&app.offerDeadline?`<p class="application-deadline">${icon('clock',13)} 截止 ${dateTime(app.offerDeadline)}</p>`:''}</button><div class="application-card-footer"><span>${displayDate(app.appliedAt||app.createdAt)}</span><select data-status="${e(app.id)}" aria-label="${e(app.company)} ${e(app.title)} 投递状态">${options(app)}</select></div></article>`).join('')||'<div class="column-empty">还没有这一步的机会<br>拖入卡片，或点击 + 记录</div>'}</section>`;}).join('')}</div></div>`:emptyState(apps.length?'当前阶段已收起':'还没有这类记录',apps.length?'关闭「收起已结束」，或点击上方阶段查看记录。':'换个关键词试试，或关闭「隐藏空列」记录新机会。');
  else content.innerHTML=apps.length?`<div class="data-table-wrap"><table class="data-table"><thead><tr><th>公司与职位</th><th>状态</th><th>投递日期</th><th>投递渠道</th><th>最近更新</th><th>操作</th></tr></thead><tbody>${apps.map(app=>`<tr><td><strong>${e(app.company)}</strong><small>${e(app.title)}${app.isSample?' · 演示':''}</small></td><td><select data-status="${e(app.id)}" aria-label="${e(app.company)} ${e(app.title)} 投递状态">${options(app)}</select></td><td>${app.appliedAt?displayDate(app.appliedAt,true):'尚未投递'}</td><td>${e(app.channel||'未填写')}</td><td>${dateTime(app.updatedAt)}</td><td><button class="text-button" data-open-application="${e(app.id)}">查看记录 ${icon('arrow',13)}</button></td></tr>`).join('')}</tbody></table></div>`:emptyState('还没有这类记录','换个关键词试试，或记录一个新机会。');
  if(currentView==='board'&&$('.board-scroll',content))$('.board-scroll',content).scrollLeft=priorScroll;
  $$('[data-open-application]',content).forEach(el=>el.onclick=()=>openApplication(ctx,el.dataset.openApplication));
  $$('[data-new-stage]',content).forEach(el=>el.onclick=()=>openApplication(ctx,null,el.dataset.newStage));
  $$('[data-status]',content).forEach(el=>el.onchange=()=>updateStatus(ctx,el.dataset.status,el.value));
  $$('[data-drag]',content).forEach(el=>{el.ondragstart=event=>{if(event.target.closest('select')){event.preventDefault();return;}event.dataTransfer.setData('text/plain',el.dataset.drag);event.dataTransfer.effectAllowed='move';el.classList.add('dragging');};el.ondragend=()=>{el.classList.remove('dragging');$$('.drag-over').forEach(x=>x.classList.remove('drag-over'));};});
  $$('[data-stage]',content).forEach(col=>{col.ondragover=event=>{event.preventDefault();event.dataTransfer.dropEffect='move';col.classList.add('drag-over');};col.ondragleave=event=>{if(!col.contains(event.relatedTarget))col.classList.remove('drag-over');};col.ondrop=event=>{event.preventDefault();col.classList.remove('drag-over');const id=event.dataTransfer.getData('text/plain');if(ctx.store.state.applications.some(a=>a.id===id))updateStatus(ctx,id,col.dataset.stage);};});
}
function updateStatus(ctx,id,status){const apps=ctx.store.state.applications,index=apps.findIndex(a=>a.id===id);if(index<0)return;apps[index]=transition(apps[index],status);ctx.save();toast(`已记录：${apps[index].company} → ${stageLabel(status)}`);if(ctx.route==='tracker')renderTracker(ctx);}
export function exportApplications(apps){download(`Jobseeker-投递记录-${localDate()}.csv`,csv([['公司','职位','城市','方向','状态','投递日期','渠道','面试时间','Offer 截止','关联简历版本','备注','演示数据'],...apps.map(a=>[a.company,a.title,a.city,a.category,stageLabel(a.status),a.appliedAt||'',a.channel,a.interviewAt||'',a.offerDeadline||'',a.resumeVersion||'',a.notes,a.isSample?'是':'否'])]),'text/csv;charset=utf-8');toast('投递记录已导出为 CSV');}
export async function openApplication(ctx,id=null,initialStatus='saved'){
  const state=ctx.store.state;const existing=id?state.applications.find(a=>a.id===id):null;if(id&&!existing){toast('这条记录已不存在','error');return;}
  const at=new Date().toISOString();const app=existing||{id:uid(),company:'',title:'',city:'',category:'自定义',status:initialStatus,channel:'',notes:'',createdAt:at,updatedAt:at,appliedAt:initialStatus==='saved'?null:at,history:[],resumeVersion:'',interviewAt:'',offerDeadline:'',isSample:false};
  let versions=[];try{versions=(await allVersions()).filter(v=>!v.sourceText&&v.facts.some(f=>f.status==='accepted'&&f.source!=='AI-SUGGEST'));}catch{}
  const dialog=modal(existing?'这一份机会的故事':'记录一个新机会',`${app.deliveryState==='uncertain'?'<p class="sample-notice">上次邮件投递未能确认结果。请核对邮箱发件记录或招聘方反馈，避免重复发送；确认后可以手动更新下方投递状态。</p>':''}<form id="application-form"><div class="form-grid"><label class="field">公司名称<input name="company" required maxlength="100" value="${e(app.company)}" placeholder="目标公司"></label><label class="field">职位名称<input name="title" required maxlength="100" value="${e(app.title)}" placeholder="目标职位"></label><label class="field">当前状态<select name="status">${STAGES.map(s=>`<option value="${s.id}" ${app.status===s.id?'selected':''}>${s.label}</option>`).join('')}</select></label><label class="field">投递日期<input name="appliedAt" type="date" value="${app.appliedAt?localDate(app.appliedAt):''}"><small>待投递可留空；开始投递后记录日期。</small></label><label class="field">投递渠道<input name="channel" value="${e(app.channel)}" placeholder="官网 / 内推 / 招聘平台"></label><label class="field">工作地点<input name="city" value="${e(app.city)}"></label><label class="field">面试时间<input name="interviewAt" type="datetime-local" value="${toLocalInput(app.interviewAt)}"></label><label class="field">Offer 答复截止<input name="offerDeadline" type="datetime-local" value="${toLocalInput(app.offerDeadline)}"></label><label class="field full">关联简历版本<select name="resumeVersion"><option value="">暂未关联</option>${versions.map(v=>`<option value="${e(v.id)}" ${app.resumeVersion===v.id?'selected':''}>${e(v.name)}</option>`).join('')}${app.resumeVersion&&!versions.some(v=>v.id===app.resumeVersion)?`<option value="${e(app.resumeVersion)}" selected>原版本（本机未找到）</option>`:''}</select></label><label class="field full">备注<textarea name="notes" rows="3" placeholder="记录沟通要点、联系人、面试准备事项…">${e(app.notes)}</textarea></label></div><div class="dialog-actions">${existing?'<button type="button" class="button danger" id="delete-application">删除记录</button>':''}<button class="button primary" type="submit">${icon('check',16)}保存记录</button></div></form>${existing?`<h3 class="section-label">进度时间线</h3><ul class="history-list">${app.history.slice().reverse().map(h=>`<li>${stageLabel(h.status)}<small>${dateTime(h.at)}</small></li>`).join('')}</ul><details><summary class="text-button">${icon('mail',15)}从邮件内容识别状态</summary><p class="caption mt-20">粘贴通知正文，在本地识别关键词；只生成候选状态，核对后保存才会生效。</p><label class="field">邮件内容<textarea id="email-content" rows="4" placeholder="例如：恭喜你通过简历筛选，现邀请你参加面试…"></textarea></label><button class="button secondary small" id="parse-email">识别候选状态</button><p class="caption mt-20" id="email-result" aria-live="polite"></p></details>`:''}`,true);
  const form=$('#application-form',dialog);
  form.onsubmit=event=>{event.preventDefault();const values=Object.fromEntries(new FormData(form));if(!values.company.trim()||!values.title.trim())return;const now=new Date().toISOString();let next={...app,company:values.company.trim(),title:values.title.trim(),channel:values.channel.trim(),city:values.city.trim(),notes:values.notes,interviewAt:values.interviewAt?new Date(values.interviewAt).toISOString():'',offerDeadline:values.offerDeadline?new Date(values.offerDeadline).toISOString():'',resumeVersion:values.resumeVersion,updatedAt:now};
    if(values.appliedAt){const prior=app.appliedAt&&localDate(app.appliedAt)===values.appliedAt;next.appliedAt=prior?app.appliedAt:new Date(values.appliedAt+'T12:00:00').toISOString();}else next.appliedAt=values.status==='saved'?app.appliedAt||null:app.appliedAt||now;
    if(existing){next=transition(next,values.status,now);const index=state.applications.findIndex(a=>a.id===id);if(index>=0)state.applications[index]=next;}else{next.status=values.status;next.history=[{status:'saved',at:next.appliedAt||now}];if(next.status!=='saved')next.history.push({status:'applied',at:next.appliedAt});if(!['saved','applied'].includes(next.status))next.history.push({status:next.status,at:now});state.applications.unshift(next);}ctx.save();dialog.close();toast('机会已记下，继续向前吧');ctx.router.refresh();};
  $('#delete-application',dialog)?.addEventListener('click',event=>{const button=event.currentTarget;if(!button.dataset.confirm){button.dataset.confirm='yes';button.textContent='确定删除这条记录？';return;}state.applications=state.applications.filter(a=>a.id!==id);ctx.save();dialog.close();toast('投递记录已删除');ctx.router.refresh();});
  $('#parse-email',dialog)?.addEventListener('click',()=>{const status=guessEmailStatus($('#email-content').value);const result=$('#email-result');if(!status){result.textContent='暂时没有识别出明确进展，请根据原文手动选择状态。';return;}result.innerHTML=`候选状态：<strong>${stageLabel(status)}</strong>。请核对原文。<button class="text-button" id="use-email-status">填入表单</button>`;$('#use-email-status').onclick=()=>{form.elements.status.value=status;result.textContent=`已填入「${stageLabel(status)}」，点击上方保存记录后生效。`;};});
}
