import assert from 'node:assert/strict';
import {mkdir,readFile} from 'node:fs/promises';
import {pathToFileURL,fileURLToPath} from 'node:url';
import {createServer} from '../server.mjs';
import {initialState} from '../js/storage.js';
import {extractResume} from '../server/documents.mjs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE?pathToFileURL(process.env.PLAYWRIGHT_MODULE).href:'playwright');
const artifacts=fileURLToPath(new URL('../artifacts/',import.meta.url));await mkdir(artifacts,{recursive:true});
const stamp='2026-10-02T01:00:00Z';
const job={id:'web-e2e',company:'测试公司',title:'前端开发工程师',city:'上海',description:'使用 React 开发可访问的网页界面。',responsibilities:['开发网页界面'],skills:['React'],salaryMin:0,salaryMax:0,remote:false,size:'',category:'联网招聘',industry:'example.org',logo:'测',tone:'sage',source:'web',url:'https://example.org/jobs/test',sourceTitle:'测试职位原文',evidence:'招聘前端开发工程师',reason:'岗位需要 React',verifiedAt:stamp,postedAt:'',availability:'待官网确认'};
let sent=0,searches=0,mailPolls=0;const aiTasks=[];
const server=createServer({key:'MOCK_ONLY',model:'qwen-plus',defaultMode:'live'}, {
 discover:async(_config,p)=>{searches++;assert.equal(p.query,'前端开发');assert.equal(p.city,'上海');return {jobs:[job],summary:'找到一个有原文依据的候选岗位。',sources:[{url:job.url,title:job.sourceTitle,readable:true}],stages:[{label:'联网搜索',count:1},{label:'读取原文',count:1},{label:'提取与筛选',count:1}],searchedAt:stamp};},
 requestAI:async(_config,task,p)=>{aiTasks.push(task);assert.equal(task,'resume');assert.equal(p.profile.name,'流程测试同学');return {model:'qwen-plus',result:{facts:[{section:'summary',text:p.profile.summary,source:'USER',sourceRef:'个人简介'},{section:'projects',text:'使用 React 完成个人网页项目。',source:'AI-INFER',sourceRef:'个人简介'}]}};},
 mail:{verify:async()=>{},readMail:async(a)=>{mailPolls++;return {cursor:sent?1:0,validity:'1',messages:sent&&a.provider==='qq'?[{id:'test-mail-1',subject:'测试公司前端岗位面试邀请',from:'hr@example.org',text:'邀请你参加前端岗位面试。',receivedAt:stamp}]:[]};},ai:async(_config,_task,p)=>({result:{events:p.messages.map(m=>({mailId:m.id,applicationId:p.applications.find(a=>a.company==='测试公司')?.id||'',status:'interview',summary:'请核对面试邀请',evidence:m.text,eventAt:'2026-10-08T10:00:00+08:00',confidence:0.98}))}}),sendMail:async(_account,m)=>{sent++;assert.equal(m.to,'hr@example.org');assert.ok(m.attachments[0].content.length>1000);return {accepted:['hr@example.org'],messageId:'test-send-1'};}}
});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true,locale:'zh-CN',reducedMotion:'reduce'});
const seed=initialState([],false);await context.addInitScript(state=>{if(!localStorage.getItem('jobpilot.workspace.v1'))localStorage.setItem('jobpilot.workspace.v1',JSON.stringify(state));},seed);
await context.route('https://example.org/**',r=>r.fulfill({contentType:'text/html',body:'<h1>Test recruiting page</h1>'}));
const page=await context.newPage(),errors=[];page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));
const state=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('jobpilot.workspace.v1')));
const nav=async route=>{await page.goto(base+'/#/'+route);await page.locator('#main-content').waitFor();};
try{
 await nav('jobs');await page.locator('[data-discovery-mode=web].active').waitFor();assert.equal(await page.locator('.job-card').count(),0);assert.equal(await page.locator('#all-jobs-count').innerText(),'0');
 await page.screenshot({path:artifacts+'agent-home.png',fullPage:true});
 await page.locator('#search-form [name=query]').fill('前端开发');await page.locator('#search-form [name=city]').selectOption('上海');await page.locator('.search-submit').click();await page.locator('.job-card').waitFor();assert.equal(searches,1);assert.equal(await page.locator('.job-card').count(),1);assert.equal(await page.locator('#all-jobs-count').innerText(),'1');await page.screenshot({path:artifacts+'agent-search.png',fullPage:true});
 await page.locator('.job-title').click();await page.getByRole('button',{name:'为此定制简历',exact:false}).click();await page.locator('#profile-form [name=name]').fill('流程测试同学');await page.locator('#profile-form [name=role]').fill('前端开发');await page.locator('#profile-form [name=email]').fill('candidate@example.org');await page.locator('#profile-form [name=summary]').fill('使用 React 完成个人网页项目，有前端项目实践经验。');await page.locator('#profile-form [name=name]').click();
 await page.locator('#generate-resume').click();await page.locator('.resume-fact.pending').first().waitFor();assert.equal(await page.locator('.resume-fact.pending').count(),2);await page.locator('#resume-deliver').click();await page.getByText('请确认或移除所有待核实内容后再投递',{exact:true}).waitFor();assert.equal(sent,0);while(await page.locator('[data-accept]').count())await page.locator('[data-accept]').first().click();assert.equal((await state()).resume.targetJobId,job.id);
 await nav('settings');await page.locator('#connect-mail-form').waitFor();
 for(const [provider,email]of [['qq','tester@qq.com'],['netease','tester@163.com']]){const form=page.locator('#connect-mail-form');await form.locator('[name=provider]').selectOption(provider);await form.locator('[name=email]').fill(email);await form.locator('[name=password]').fill('TEST_AUTHORIZATION_CODE');await form.locator('[name=consent]').check();await form.getByRole('button',{name:'连接邮箱',exact:true}).click();await page.locator('.mail-account strong').filter({hasText:email}).waitFor();assert.equal(await form.locator('[name=password]').inputValue(),'');}
 assert.equal(await page.locator('.mail-account').count(),2);assert.ok(!JSON.stringify(await state()).includes('TEST_AUTHORIZATION_CODE'));await page.screenshot({path:artifacts+'agent-mail-settings.png',fullPage:true});
 await nav('resume');await page.locator('#resume-deliver').waitFor();await page.locator('#resume-deliver').click();await page.locator('#delivery-mail-form').waitFor();const popupPromise=page.waitForEvent('popup');await page.locator('#open-application-page').click();const popup=await popupPromise;await popup.close();assert.equal((await state()).applications[0].status,'saved');
 await page.locator('#delivery-mail-form [name=to]').fill('hr@example.org');await page.locator('#delivery-mail-form').getByRole('button',{name:'生成投递预览'}).click();await page.locator('#send-delivery').waitFor();await page.locator('#send-delivery').click();assert.equal(sent,0);const downloaded=page.waitForEvent('download');await page.locator('#review-delivery-attachment').click();const file=await downloaded,buffer=await readFile(await file.path());const parsed=await extractResume({filename:'application.docx',content:buffer.toString('base64')});assert.ok(parsed.text.includes('流程测试同学'));await page.screenshot({path:artifacts+'agent-delivery-preview.png',fullPage:true});await page.locator('#confirm-delivery-content').check();await page.locator('#send-delivery').click();await page.locator('#tracker-mail-events').waitFor();assert.equal(sent,1);assert.equal((await state()).applications[0].status,'applied');assert.equal((await state()).agent.pendingSends.length,0);
 await nav('settings');await page.locator('#sync-mail').click();await page.getByText('本轮检查结束，请查看账户同步状态和待确认进展',{exact:true}).waitFor();assert.equal((await state()).applications[0].status,'applied');await nav('tracker');await page.locator('#tracker-mail-events').click();await page.locator('[data-accept-mail]').waitFor();await page.screenshot({path:artifacts+'agent-mail-review.png',fullPage:true});await page.locator('[data-accept-mail]').click();assert.equal((await state()).applications[0].status,'interview');assert.equal((await state()).agent.mailEvents[0].review,'accepted');assert.ok((await state()).applications[0].interviewAt);await page.getByRole('button',{name:'关闭对话框'}).click();
 await page.locator('#notifications-button').click();await page.getByRole('button',{name:'关闭对话框'}).click();
 await page.setViewportSize({width:390,height:844});for(const route of ['jobs','resume','tracker','settings']){await nav(route);await page.waitForTimeout(150);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),route+' horizontal overflow');await page.screenshot({path:artifacts+'agent-mobile-'+route+'.png',fullPage:true});}
 assert.deepEqual(errors,[]);assert.equal(sent,1);assert.deepEqual(aiTasks,['resume']);console.log('Agent E2E passed: search → profile → reviewed resume → two mailboxes → frozen Word preview → confirmed send → tracker → user-confirmed mail progress; four mobile layouts. AI, IMAP and SMTP are simulated; local APIs and DOCX generation are real.');
}catch(error){await page.screenshot({path:artifacts+'agent-e2e-failure.png',fullPage:true});console.error('Browser errors:',errors);console.error(await page.locator('#toast-stack').innerText());throw error;}
finally{await context.close();await browser.close();await new Promise(r=>{server.close(r);server.closeAllConnections();});}

