import assert from 'node:assert/strict';
import {readFile,mkdir} from 'node:fs/promises';
import {pathToFileURL,fileURLToPath} from 'node:url';
import {createServer} from '../server.mjs';
import {extractResume} from '../server/documents.mjs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE?pathToFileURL(process.env.PLAYWRIGHT_MODULE).href:'playwright');
const artifacts=fileURLToPath(new URL('../artifacts/',import.meta.url));await mkdir(artifacts,{recursive:true});
const server=createServer({key:'',defaultMode:'demo',model:'',port:0});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true,locale:'zh-CN'});
const page=await context.newPage(),errors=[],deliveryRequests=[];page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/\/api\/mail\/(prepare|send|attachment)/.test(r.url()))deliveryRequests.push(r.url());});
try{
 await page.goto(`http://127.0.0.1:${server.address().port}/#/resume`);
 await page.getByRole('button',{name:'编辑与定制',exact:true}).click();
 assert.equal(await page.locator('#resume-target').inputValue(),'demo-001');
 await page.locator('#generate-resume').click();await page.locator('.rewrite-original').first().waitFor();
 assert.equal(await page.locator('.rewrite-original').count(),5);
 await page.locator('#resume-deliver').click();await page.getByText('请确认或移除所有待核实内容后再投递',{exact:true}).waitFor();
 await page.locator('.rewrite-original summary').first().click();
 await page.screenshot({path:artifacts+'demo-rewrite-desktop.png',fullPage:true});
 await page.locator('#accept-originals').click();
 while(await page.locator('[data-accept]').count())await page.locator('[data-accept]').first().click();
 while(await page.locator('.suggestion [data-reject]').count())await page.locator('.suggestion [data-reject]').first().click();
 await page.locator('#preview-finished').click();assert.equal(await page.locator('#resume-preview .source-row').count(),0);
 assert.ok((await page.locator('#resume-preview').innerText()).includes('820ms'));
 await page.screenshot({path:artifacts+'demo-finished-desktop.png',fullPage:true});
 await page.locator('#resume-deliver').click();await page.locator('#send-demo-delivery').waitFor();
 const downloadPromise=page.waitForEvent('download');await page.locator('#demo-delivery-word').click();const download=await downloadPromise;
 const docx=await extractResume({filename:download.suggestedFilename(),content:(await readFile(await download.path())).toString('base64')});assert.ok(docx.text.includes('820ms'));assert.ok(!docx.text.includes('原始输入'));
 await page.locator('#send-demo-delivery').click();await page.getByText('请先勾选核对确认',{exact:true}).waitFor();
 await page.screenshot({path:artifacts+'demo-delivery-preview.png',fullPage:true});
 await page.locator('#confirm-demo-delivery').check();await page.locator('#send-demo-delivery').click();await page.locator('#view-demo-application').waitFor();
 await page.screenshot({path:artifacts+'demo-delivery-receipt.png',fullPage:true});
 await page.locator('#view-demo-application').click();await page.locator('dialog[open] [name=resumeVersion]').waitFor();
 assert.ok(await page.locator('dialog[open] [name=resumeVersion]').inputValue());
 await page.getByRole('button',{name:'关闭对话框'}).click();await page.reload();
 const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('jobpilot.workspace.v1'))),app=state.applications.find(a=>a.jobId==='demo-001');
 assert.equal(app.status,'applied');assert.equal(app.deliveryState,'simulated');assert.equal(state.applications.length,12);
 await page.getByRole('link',{name:'简历工作室',exact:true}).first().click();await page.getByRole('button',{name:'简历库',exact:true}).click();await page.locator('.library-card').waitFor();
 assert.equal(await page.locator('.library-card').count(),1);
 await page.getByRole('button',{name:'编辑与定制',exact:true}).click();await page.locator('#preview-review').click();assert.equal(await page.locator('.rewrite-original').count(),5);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:artifacts+'demo-rewrite-mobile.png',fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await page.locator('#resume-deliver').click();await page.locator('#send-demo-delivery').waitFor();await page.screenshot({path:artifacts+'demo-delivery-mobile.png',fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 assert.deepEqual(deliveryRequests,[]);assert.deepEqual(errors,[]);
 console.log('Demo E2E passed: rewrite comparison, confirmation gating, finished layout, Word attachment, simulated delivery, receipt, version linkage, reload persistence, mobile layout; no mail-send endpoints called.');
}catch(error){await page.screenshot({path:artifacts+'demo-e2e-failure.png',fullPage:true});throw error;}
finally{await context.close();await browser.close();await new Promise(resolve=>{server.close(resolve);server.closeAllConnections();});}
