/** Optional browser regression suite. Requires Playwright + a Chromium installation. */
import assert from 'node:assert/strict';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { pathToFileURL, fileURLToPath } from 'node:url';
import path from 'node:path';
let chromium;
try { ({chromium}=await import(process.env.PLAYWRIGHT_MODULE ? pathToFileURL(process.env.PLAYWRIGHT_MODULE).href : 'playwright')); }
catch { console.error('Optional E2E dependency missing. Install Playwright and Chromium, then run npm run test:e2e. See README.md.'); process.exit(1); }
const base=process.env.BASE_URL||'http://127.0.0.1:4173';
const artifacts=fileURLToPath(new URL('../artifacts/',import.meta.url));await mkdir(artifacts,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true,locale:'zh-CN',timezoneId:'Asia/Shanghai',reducedMotion:'reduce',...(process.env.RECORD_DEMO?{recordVideo:{dir:path.join(artifacts,'video'),size:{width:1440,height:1000}}}:{})});
const aiRequests=[],mailRequests=[];let analysisFails=false,generatedFacts=[];
await context.route('**/api/**',async route=>{
  const request=route.request(),pathname=new URL(request.url()).pathname;
  if(pathname==='/api/config')return route.fulfill({json:{configured:true,provider:'qwen-local',model:'qwen-test',setupId:'unified-ai-e2e',csrfToken:'test-token',capabilities:{unifiedAI:true}}});
  if(pathname.startsWith('/api/mail/')){mailRequests.push(pathname);return route.fulfill({json:{accounts:[],events:[]}});}
  if(pathname!=='/api/ai')return route.fulfill({status:501,json:{error:'Unexpected E2E API request: '+pathname}});
  const {task,payload}=request.postDataJSON();aiRequests.push({task,payload});assert.equal(request.headers()['x-jobseeker-token'],'test-token');
  if(task==='analysis'&&analysisFails)return route.fulfill({status:503,json:{error:'测试服务暂时不可用 <script>不可执行</script>'}});
  let result;
  if(task==='match')result=payload.jobs?{matches:payload.jobs.map(job=>({id:job.id,score:88,analysis:'AI 测试匹配结果',gaps:[]})),strategy:'AI 已核对示例岗位与当前档案'}:{score:88,analysis:'AI 测试匹配结果',gaps:[]};
  else if(task==='resume'){
    generatedFacts=[...payload.sourceFacts.map(fact=>({...fact,source:'USER'})),{section:'summary',text:'待核实的 AI 改写测试内容',source:'AI-INFER',sourceRef:'简介'},{section:'projects',text:'如有 Node.js 真实经验，请补充。',source:'AI-SUGGEST',sourceRef:'岗位要求'}];result={facts:generatedFacts};
  }else if(task==='analysis')result={summary:'AI 已分析示例与真实投递记录。',bottlenecks:['继续记录筛选反馈'],suggestions:['准备下一轮面试']};
  else if(task==='connection')result={ok:true};
  else return route.fulfill({status:400,json:{error:'Unexpected E2E AI task: '+task}});
  return route.fulfill({json:{result,model:'qwen-test'}});
});
const page=await context.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));page.setDefaultTimeout(7000);
const check=(condition,message)=>assert.ok(condition,message);
try {
  await page.goto(base);await page.locator('.job-card').first().waitFor();check(await page.locator('.job-card').count()===6,'six jobs on first page');check((await page.locator('#mode-label').innerText()).trim()==='AI 已连接','sample workspace uses configured AI');
  await page.screenshot({path:path.join(artifacts,'desktop-jobs.png'),fullPage:true});
  await page.getByRole('button',{name:'产品经理',exact:true}).click();await page.getByLabel('工作地点',{exact:true}).selectOption('上海');await page.getByRole('button',{name:'发现好机会'}).click();await page.getByText('AI 已核对示例岗位与当前档案',{exact:false}).waitFor();check(await page.locator('.job-card').count()===1,'keyword and city filters');check(aiRequests.some(({task,payload})=>task==='match'&&payload.jobs?.every(job=>job.id.startsWith('demo-'))),'sample jobs use AI request');
  await page.getByRole('button',{name:'重置',exact:true}).click();await page.getByRole('button',{name:'收藏 山海网络 前端开发实习生',exact:true}).click();
  await page.getByRole('link',{name:'简历工作室',exact:true}).click();await page.getByRole('button',{name:'编辑与定制',exact:true}).click();await page.getByRole('combobox',{name:'目标机会',exact:true}).selectOption('demo-031');await page.getByRole('button',{name:'AI 优化并排版',exact:true}).click();await page.getByText('AI 内容已生成，请逐条核实再确认',{exact:true}).waitFor();check(await page.locator('.resume-fact.pending').count()===generatedFacts.length,'all AI generated facts require review');check(aiRequests.some(({task,payload})=>task==='resume'&&payload.profile.isSample),'sample profile uses AI request');
  await page.locator('#accept-originals').click();check(await page.locator('.resume-fact.pending').count()===2,'AI inference and supplement still need review');const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Markdown',exact:true}).click();const download=await downloadPromise;const markdown=await readFile(await download.path(),'utf8');check(markdown.includes('拾光 · 阅读笔记'),'confirmed project exported');check(!markdown.includes('如有 Node.js')&&!markdown.includes('待核实的 AI 改写测试内容'),'pending inference and suggestions excluded');
  await page.getByRole('button',{name:'保存版本',exact:true}).click();await page.getByRole('button',{name:'简历版本',exact:true}).click();await page.locator('.version-item').first().waitFor();check(await page.locator('.version-item').count()===1,'IndexedDB version saved');await page.getByRole('button',{name:'关闭对话框'}).click();
  await page.screenshot({path:path.join(artifacts,'desktop-resume.png'),fullPage:true});
  await page.locator('#desktop-nav [data-nav="tracker"]').click();await page.getByRole('button',{name:'记录新机会'}).click();await page.getByRole('textbox',{name:'公司名称',exact:true}).fill('E2E 公司');await page.getByRole('textbox',{name:'职位名称',exact:true}).fill('测试工程师');await page.getByRole('combobox',{name:'当前状态',exact:true}).selectOption('applied');await page.getByRole('combobox',{name:'关联简历版本',exact:true}).selectOption({index:1});await page.getByRole('button',{name:'保存记录',exact:true}).click();
  await page.getByRole('combobox',{name:'E2E 公司 测试工程师 投递状态',exact:true}).selectOption('screening');
  const card=page.locator('.application-card').filter({hasText:'E2E 公司'});await card.getByRole('combobox',{name:'E2E 公司 测试工程师 投递状态',exact:true}).selectOption('test');check(await page.locator('[data-stage="test"] .application-card').filter({hasText:'E2E 公司'}).count()===1,'status control updates board');
  await page.getByRole('button',{name:'列表',exact:true}).click();await page.getByRole('textbox',{name:'搜索投递记录'}).fill('E2E 公司');await page.getByRole('button',{name:'查看记录',exact:true}).click();check((await page.locator('.history-list').innerText()).includes('笔试'),'status history records board updates');await page.getByRole('button',{name:'关闭对话框'}).click();
  await page.locator('#desktop-nav [data-nav="insights"]').click();await page.locator('#funnel-chart').waitFor();check(await page.locator('canvas').count()===2,'charts rendered');await page.locator('#analyze-progress').click();await page.getByText('AI 已分析示例与真实投递记录。',{exact:true}).waitFor();const analysis=aiRequests.find(request=>request.task==='analysis');check(analysis.payload.applications.some(app=>app.isSample)&&analysis.payload.applications.some(app=>!app.isSample),'AI analyzes sample and real records together');
  analysisFails=true;await page.locator('#analyze-progress').click();await page.locator('#progress-advice [role=alert]').waitFor();check((await page.locator('#progress-advice').innerText()).includes('测试服务暂时不可用 <script>不可执行</script>'),'AI failure reports actual escaped error');check(await page.locator('#progress-advice script').count()===0,'AI error text cannot execute markup');check(!(await page.locator('#progress-advice').innerText()).includes('本地规则建议'),'AI failure does not substitute local advice');analysisFails=false;await page.locator('#analyze-progress').click();await page.getByText('AI 已分析示例与真实投递记录。',{exact:true}).waitFor();await page.screenshot({path:path.join(artifacts,'desktop-insights.png'),fullPage:true});
  await page.locator('#settings-link').click();await page.locator('#ai-settings-form').waitFor();check(await page.locator('#test-ai').isVisible(),'AI controls are available for sample data');check(await page.locator('[name=mode]').count()===0,'AI has no demo/live mode selector');await page.getByRole('button',{name:'夜间手账',exact:false}).click();await page.reload();await page.locator('#ai-settings-form').waitFor();check(await page.locator('html').getAttribute('data-theme')==='dark','theme persists');await page.getByRole('button',{name:'日光纸张',exact:false}).click();
  const backupDownloadPromise=page.waitForEvent('download');await page.locator('#export-backup').click();const backupDownload=await backupDownloadPromise;const backup=JSON.parse(await readFile(await backupDownload.path(),'utf8'));check(backup.applications.length===14,'backup includes new application');check(backup.versions.length===1,'backup includes IndexedDB');check(!JSON.stringify(backup).includes('apiKey'),'backup excludes API key');
  const backupPath=path.join(artifacts,'test-backup.json');await writeFile(backupPath,JSON.stringify({...backup,settings:{...backup.settings,mode:'demo',model:'obsolete-backup-model'}}));await page.locator('#backup-file').setInputFiles(backupPath);await page.locator('#confirm-import').click();await page.locator('#app-dialog').waitFor({state:'hidden'});check((await page.locator('.mode-pill').innerText()).trim()==='AI 已连接','import preserves AI connection');const restoredSettings=await page.evaluate(()=>JSON.parse(localStorage.getItem('jobpilot.workspace.v1')).settings);check(restoredSettings.mode==='live'&&restoredSettings.model==='qwen-test'&&restoredSettings.consent,'legacy backup keeps current AI settings');
  await page.locator('#desktop-nav [data-nav="resume"]').click();await page.evaluate(()=>{window.print=()=>{document.documentElement.dataset.printRequested='true';};});await page.locator('#export-pdf').click();check(await page.locator('html').getAttribute('data-print-requested')==='true','PDF button invokes native print');check(await page.locator('#print-root .resume-fact').count()===generatedFacts.length-2,'PDF contains only confirmed original facts');check(!(await page.locator('#print-root').textContent()).includes('如有 Node.js'),'PDF excludes supplement suggestions');await page.emulateMedia({media:'print'});await page.pdf({path:path.join(artifacts,'resume-print.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true});await page.emulateMedia({media:'screen'});
  await page.setViewportSize({width:390,height:844});
  for(const route of ['jobs','resume','tracker','insights','settings']){await page.goto(`${base}/#/${route}`);await page.locator('main h1').waitFor();check(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),`${route} has no page-level mobile overflow`);await page.screenshot({path:path.join(artifacts,`mobile-${route}.png`),fullPage:true});}
  check(!mailRequests.some(pathname=>/\/(prepare|send|attachment|connect|sync)$/.test(pathname)),'no real mail operations requested');check(errors.length===0,errors.join('\n'));console.log('E2E passed: unified AI with sample data, explicit AI failures and retry, search, bookmarks, provenance, exports, versions, board status/history, charts, AI-preserving legacy backup restore, theme persistence, and 5 mobile views. All API responses mocked; no real mail operations.');
} catch(error){await page.screenshot({path:path.join(artifacts,'e2e-failure.png'),fullPage:true});console.error(await page.locator('#toast-stack').innerText());console.error(errors);throw error;} finally {await context.close();await browser.close();}
